--------------------------------------------------------------------------------
-- OAGWBG_R_BUDGETOVERLAP  (v2 — perf fix 2026-08-27)
--------------------------------------------------------------------------------
-- ใช้สำหรับ : แบบรายงานผลการเบิกจ่าย (ReportBudgetOverlap Template "3")
--
-- ปัญหาเดิม : 31.6 วิ (หลังแก้ V_BUDGETRESERVEDITEM แล้วเหลือ 24.2 วิ)
--   APPS.OAGPO_TRANSACTION_STATUS_V ถูก scan 2 รอบแยกกัน :
--     รอบที่ 1 — ข้างใน OAGWBG_V_BUDGETRESERVEDITEM (~11 วิ)
--     รอบที่ 2 — subquery TSV ของ view นี้เอง (~10 วิ)
--   เพราะอยู่คนละ view Oracle จึงแชร์ผลกันไม่ได้
--
-- สิ่งที่เปลี่ยน :
--   1) เพิ่ม CTE `TSV_RAW` ครอบ APPS.OAGPO_TRANSACTION_STATUS_V
--   2) inline logic ของ OAGWBG_V_BUDGETRESERVEDITEM เข้ามา แล้วให้อ้าง TSV_RAW
--      → EBS ถูกอ่านครั้งเดียวสำหรับทั้ง query แทนที่จะ 2 รอบ
--   3) subquery TSV เดิม → อ้าง TSV_RAW
--
--   ⚠️ SELECT list / WHERE / join condition คงไว้เหมือนเดิมทุกตัวอักษร
--   (BRSI.STATUSNAME ถูก comment ทิ้งไว้ใน SELECT อยู่แล้ว จึงไม่ต้อง join MASTERSTATUS)
--
-- rollback : rollback_view_budgetoverlap.sql
--------------------------------------------------------------------------------

CREATE OR REPLACE VIEW OAGWBG_R_BUDGETOVERLAP AS
WITH TSV_RAW AS (
    SELECT /*+ MATERIALIZE */
           PR_STATUS, PR_BUDGET_ACCOUNT,
           PO_STATUS, PO_BUDGET_ACCOUNT,
           PO_NUMBER, PO_LINE_ID, PO_CONTRACT_DATE
    FROM   APPS.OAGPO_TRANSACTION_STATUS_V
)
SELECT
    BRS.ID AS BUDGETRESERVEDID,
    COALESCE(CAT.BUDGETYEAR, BRSI.BUDGETYEAR, BRS.BUDGETYEAR) AS BUDGETYEAR,
    BRS.TRANSFERNO,
    BRS.RESERVATIONNAME,
    BRS.RESERVATIONTYPE,
    BRS.BUDGETRESERVEDTYPE,
    BRS.REASON,
    BRS.CREATEON AS RESERVEDDATE,
    BRS.DEPARTMENTID,
    DEPTV.NAME AS DEPARTMENTNAME,
    BRS.COSTCENTERID,
    COSTV.NAME AS COSTCENTERNAME,
    COSTV.REGIONID,
    BRS.BUDGETRESERVEDREGION,
    BRSI.ID AS ITEMID,
    BRSI.DESCRIPTION,
    BRSI.SUPPLIER,
    BRSI.BUDGETRESERVEDTYPE AS ITEMRESERVEDTYPE,
    BRSI.TOTALHASPRAMOUNT AS PRAMOUNT,
    BRSI.TOTALHASPOAMOUNT AS POAMOUNT,
    CASE 
        WHEN BUDGETRESERVEDREGION = 'C' THEN CAT.TOTALRESERVEDAMOUNT
        ELSE BRSI.TOTALBALANCEAMOUNT
    END AS TOTALBALANCEAMOUNT,
    BRSI.REASON AS ITEMREASON,
    CASE 
        WHEN BRS.BUDGETRESERVEDREGION = 'C' OR BRS.BUDGETRESERVEDREGION = 'P'  THEN BRS.STATUSID
        ELSE BRSI.STATUSID
    END AS STATUSID,
--    CASE 
--        WHEN BRS.BUDGETRESERVEDREGION = 'C' OR BRS.BUDGETRESERVEDREGION = 'P' THEN BRS.STATUSNAME
--        ELSE BRSI.STATUSNAME
--    END AS STATUSNAME,
    CASE
            WHEN BRS.ROUNDINTERFACE = 1 THEN 'กันเงิน'
            WHEN BRS.ROUNDINTERFACE > 1 THEN 'ขยายระยะเวลา'
            ELSE 'ร่าง'
    END AS STATUSNAME,
    BRSI.CREATEON AS RESERVEDITEMDATE,
    TO_CHAR(BRSI.CREATEON,'MM') AS RESERVEDMONTH,
    BRSI.PO_CONTRACT,
    BRSI.CONTRACT_CARRY_FORWARD_PO  AS PO_CONTRACT_DATE,
    BRSI.PO_CONTRACT_START_DATE,
    BRSI.PO_CONTRACT_DUE_DATE,
    BRSI.BOOKNUMBER,
    BRSI.COSTCENTERCODE,
    BRSI.ACCOUNTCODE,
    CASE 
        WHEN BUDGETRESERVEDREGION = 'C' AND BRSI.ACCOUNTCODE IS NOT NULL THEN  REGEXP_SUBSTR(BRSI.ACCOUNTCODE, '[^.]+', 1, 4)
        WHEN BUDGETRESERVEDREGION = 'P' AND BRSI.ACCOUNTCODE IS NOT NULL THEN  REGEXP_SUBSTR(BRSI.ACCOUNTCODE, '[^.]+', 1, 4)
        ELSE BRS.BUDGETSOURCEID
    END AS BUDGETSOURCEID,
    REGEXP_SUBSTR(BRSI.ACCOUNTCODE, '[^.]+', 1, 9) AS BUDGETCODE,
    CAT.CATEGORYID,
    CAT.CATEGORYNAME,
    CAT.CATEGORY_CODE,
    CAT.TOTALRESERVEDAMOUNT,
    CAT.BUDGETPLANID,
    CAT.PLAN_NAME,
    CAT.PRODUCTID,
    CAT.PRODUCT_NAME,
    CAT.ACTIVITYID,
    CAT.ACTIVITY_NAME,
    CAT.BUDGETCODEID,
    CASE
        WHEN BRSI.BUDGETRESERVEDTYPE = 'O' THEN 'มีหนี้'
        WHEN BRSI.BUDGETRESERVEDTYPE = 'R' THEN 'ไม่มีหนี้'
        WHEN BRSI.BUDGETRESERVEDTYPE = 'EXPAND_PO' THEN 'มีหนี้'
        WHEN BRSI.BUDGETRESERVEDTYPE = 'EXPAND_PR' THEN 'ไม่มีหนี้'
        ELSE 'ไม่ระบุ'
    END AS RESERVEDTYPENAME,
     CASE
              WHEN (CASE WHEN BRS.BUDGETRESERVEDREGION = 'C' THEN BRS.STATUSID ELSE BRSI.STATUSID END) = 90102 THEN 'ขยายเวลา'
              WHEN (CASE WHEN BRS.BUDGETRESERVEDREGION = 'C' THEN BRS.STATUSID ELSE BRSI.STATUSID END) = 90109 THEN 'ยกเลิก'
              WHEN (CASE WHEN BRS.BUDGETRESERVEDREGION = 'C' THEN BRS.STATUSID ELSE BRSI.STATUSID END) = 90101 THEN 'ปกติ'
               WHEN (CASE WHEN BRS.BUDGETRESERVEDREGION = 'C' THEN BRS.STATUSID ELSE BRSI.STATUSID END) = 20202 THEN 'พิจารณาแล้ว'
              ELSE 'อื่น ๆ'
          END AS RESERVEDSTATUSNAME,
    TSV.PR_STATUS,
    TSV.PO_STATUS
FROM OAGWBG_V_BUDGETRESERVED BRS 
LEFT JOIN (
    -- แทน OAGWBG_V_BUDGETRESERVEDITEM : อ่านตารางจริง + คำนวณ CONTRACT_CARRY_FORWARD_PO
    -- ด้วย logic เดิมทุกตัวอักษร (อ้าง TSV_RAW แทน APPS.OAGPO_TRANSACTION_STATUS_V)
    SELECT BR0.ID,
           BR0.BUDGETREVERSEDID,
           BR0.BUDGETYEAR,
           BR0.DESCRIPTION,
           BR0.SUPPLIER,
           BR0.BUDGETRESERVEDTYPE,
           BR0.TOTALHASPRAMOUNT,
           BR0.TOTALHASPOAMOUNT,
           BR0.TOTALBALANCEAMOUNT,
           BR0.REASON,
           BR0.STATUSID,
           BR0.CREATEON,
           BR0.PO_CONTRACT,
           BR0.PO_CONTRACT_START_DATE,
           BR0.PO_CONTRACT_DUE_DATE,
           BR0.BOOKNUMBER,
           BR0.COSTCENTERCODE,
           BR0.ACCOUNTCODE,
           CFPO.PO_CONTRACT_DATE            AS CONTRACT_CARRY_FORWARD_PO
    FROM       OAGWBG_BUDGETRESERVEDITEM BR0
    LEFT JOIN  OAGWBG_BUDGETRESERVEDITEM BR1 ON BR0.PARENTID = BR1.ID
    LEFT JOIN  TSV_RAW CFPO
           ON (
                CFPO.PR_BUDGET_ACCOUNT = BR0.ACCOUNTCODE
                OR (
                    CFPO.PO_BUDGET_ACCOUNT = BR0.ACCOUNTCODE
                    AND NOT EXISTS (
                        SELECT 1
                        FROM   TSV_RAW X
                        WHERE  X.PO_NUMBER  = BR0.BOOKNUMBER
                          AND  X.PO_LINE_ID = COALESCE(BR0.LINEID, BR1.LINEID)
                          AND  X.PR_BUDGET_ACCOUNT = BR0.ACCOUNTCODE
                    )
                )
              )
          AND CFPO.PO_NUMBER  = BR0.BOOKNUMBER
          AND CFPO.PO_LINE_ID = COALESCE(BR0.LINEID, BR1.LINEID)
) BRSI
       ON BRS.ID = BRSI.BUDGETREVERSEDID
LEFT JOIN OAGWBG_V_BUDGETRESERVED_CATEGORY CAT 
       ON BRS.ID = CAT.BUDGETRESERVEDID
LEFT JOIN OAGWBG_V_EXT_OAGGL_DEPARTMENT_V DEPTV 
       ON BRS.DEPARTMENTID = DEPTV.ID
LEFT JOIN OAGWBG_V_EXT_OAGGL_COST_CENTER_V COSTV 
       ON BRS.COSTCENTERID = COSTV.ID
LEFT JOIN (
    SELECT PR_BUDGET_ACCOUNT, PO_BUDGET_ACCOUNT,
           MAX(PR_STATUS) AS PR_STATUS,
           MAX(PO_STATUS) AS PO_STATUS
    FROM TSV_RAW
    GROUP BY PR_BUDGET_ACCOUNT, PO_BUDGET_ACCOUNT
) TSV ON BRSI.ACCOUNTCODE = TSV.PR_BUDGET_ACCOUNT
     AND BRSI.ACCOUNTCODE = TSV.PO_BUDGET_ACCOUNT
