CREATE OR REPLACE VIEW OAGWBG_R_BUDGETOVERLAP_EXPAND AS
SELECT
    -- ข้อมูลหลักจากหัวกันเงิน
    BRS.ID AS BUDGETRESERVEDID,
    COALESCE(BRSI.BUDGETYEAR, BRS.BUDGETYEAR) AS BUDGETYEAR,
    BRS.TRANSFERNO,
    BRS.RESERVATIONNAME,
    BRS.RESERVATIONTYPE,
    BRS.BUDGETRESERVEDTYPE,
    SU.DEPARTMENTID AS DEPARTMENTID_CREATER,
    SU.DEPARTMENTNAME AS DEPARTMENTNAME_CREATER,
    SU.COSTCENTERID AS COSTCENTERID_CREATER,
    SU.COSTCENTERNAME AS COSTCENTERNAME_CREATER,
    BRS.REASON,
    BRS.CREATEON AS RESERVEDDATE,
    BRS.DEPARTMENTID,
    DEPTV.NAME AS DEPARTMENTNAME,
    BRS.COSTCENTERID,
    COSTV.NAME AS COSTCENTERNAME,
    COSTV.REGIONID,
    BRS.BUDGETRESERVEDREGION ,
    
    -- ข้อมูลจากรายการกันเงิน (Item)
    BRSI.ID AS ITEMID,
    CASE WHEN  BRSI.BUDGETRESERVEDTYPE = 'EXPAND_LUMP' OR BRSI.BUDGETRESERVEDTYPE = 'CANCEL_LUMP' THEN  BR.CATEGORYNAME 
    ELSE BRSI.DESCRIPTION END AS DESCRIPTION,
    BRSI.SUPPLIER,
    BRSI.BUDGETRESERVEDTYPE AS ITEMRESERVEDTYPE,
    BRSI.TOTALHASPRAMOUNT AS PRAMOUNT,
    CASE WHEN  BRSI.BUDGETRESERVEDTYPE = 'EXPAND_LUMP' OR BRSI.BUDGETRESERVEDTYPE = 'CANCEL_LUMP' THEN BRSI.USAGEAMOUNT
    ELSE BRSI.TOTALHASPOAMOUNT END AS POAMOUNT, 
    
    BRSI.REASON AS ITEMREASON,
    CASE 
      WHEN BRS.BUDGETRESERVEDREGION = 'C' THEN BRSI.STATUSID
      ELSE BRS.STATUSID
    END AS STATUSID,
--    CASE 
--      WHEN BRS.BUDGETRESERVEDREGION = 'C' THEN BRSI.STATUSNAME
--      ELSE BRS.STATUSNAME
--    END AS STATUSNAME,
    CASE
            WHEN BRS.ROUNDINTERFACE = 1 THEN 'กันเงิน'
            WHEN BRS.ROUNDINTERFACE > 1 THEN 'ขยายระยะเวลา'
            ELSE 'ร่าง'
    END AS STATUSNAME ,
    
    BRSI.CREATEON AS RESERVEDITEMDATE,
    TO_CHAR(BRSI.CREATEON,'MM') AS RESERVEDMONTH,
    BRSI.PO_CONTRACT,
    BRSI.PO_CONTRACT_START_DATE,
    BRSI.PO_CONTRACT_DUE_DATE,
    BRSI.BOOKNUMBER,
    BRSI.COSTCENTERCODE,
    BRSI.ACCOUNTCODE,

    -- ดึงรหัส segment ที่จำเป็น 
    CASE BUDGETRESERVEDREGION
            WHEN 'C' THEN REGEXP_SUBSTR(BRSI.ACCOUNTCODE, '[^.]+', 1, 4)
            WHEN 'P' THEN REGEXP_SUBSTR(BRSI.ACCOUNTCODE, '[^.]+', 1, 4)
            ELSE BRS.BUDGETSOURCEID
    END AS BUDGETSOURCEID,
    
    REGEXP_SUBSTR(BRSI.ACCOUNTCODE, '[^.]+', 1, 9) AS BUDGETCODE,


    -- แปลงประเภทการกันเงิน (เพิ่มเรื่องขยายเวลาแล้ว)
    CASE
         WHEN BRSI.BUDGETRESERVEDTYPE = 'O' THEN 'มีหนี้'
         WHEN BRSI.BUDGETRESERVEDTYPE = 'R' THEN 'ไม่มีหนี้'
         WHEN BRSI.BUDGETRESERVEDTYPE = 'EXPAND_PO' THEN 'มีหนี้'
         WHEN BRSI.BUDGETRESERVEDTYPE = 'EXPAND_PR' THEN 'ไม่มีหนี้'
         WHEN BRSI.BUDGETRESERVEDTYPE = 'CANCEL_PO' THEN 'มีหนี้'
         WHEN BRSI.BUDGETRESERVEDTYPE = 'CANCEL_PR' THEN 'ไม่มีหนี้'
         WHEN BRSI.BUDGETRESERVEDTYPE = 'EXPAND_LUMP' THEN 'ไม่มีหนี้'
         WHEN BRSI.BUDGETRESERVEDTYPE = 'CANCEL_LUMP' THEN 'ไม่มีหนี้'
        ELSE 'ไม่ระบุ'
    END AS RESERVEDTYPENAME,

    -- แสดงสถานะรายการตาม StatusId
          CASE
              WHEN (CASE WHEN BRS.BUDGETRESERVEDREGION = 'C' THEN BRS.STATUSID ELSE BRSI.STATUSID END) = 90102 THEN 'ขยายเวลา'
              WHEN (CASE WHEN BRS.BUDGETRESERVEDREGION = 'C' THEN BRS.STATUSID ELSE BRSI.STATUSID END) = 90109 THEN 'ยกเลิก'
              WHEN (CASE WHEN BRS.BUDGETRESERVEDREGION = 'C' THEN BRS.STATUSID ELSE BRSI.STATUSID END) = 90101 THEN 'ปกติ'
               WHEN (CASE WHEN BRS.BUDGETRESERVEDREGION = 'C' THEN BRS.STATUSID ELSE BRSI.STATUSID END) = 20202 THEN 'พิจารณาแล้ว'
              ELSE 'อื่น ๆ'
          END AS RESERVEDSTATUSNAME,

    -- ใช้ใน Template 2: รายงานขยายเวลา
          CASE
              WHEN (CASE WHEN BRS.BUDGETRESERVEDREGION = 'C' THEN BRS.STATUSID ELSE BRSI.STATUSID END) = 90102 
              THEN 'ขยาย(กันต่อ)'
              ELSE NULL
          END AS EXTENSIONSTATUS,
          
    -- สถานะ PR/PO
        CASE
            WHEN BRSI.BUDGETRESERVEDTYPE IN ('R','EXPAND_PR')
            THEN TSV.PR_STATUS
        END AS PR_STATUS,
        
        CASE
            WHEN BRSI.BUDGETRESERVEDTYPE IN ('O','EXPAND_PO')
            THEN TSV.PO_STATUS
        END AS PO_STATUS,
   BRSI.CONTRACT_CARRY_FORWARD_PO AS CONTRACT_CARRY_FORWARD_PO,
   BRSI.RESERVEDNO_ADD,
   BRSI.OVERLAPROUND
FROM OAGWBG_V_BUDGETRESERVED BRS 
LEFT JOIN OAGWBG_V_BUDGETRESERVEDITEM BRSI
       ON BRS.ID = BRSI.BUDGETREVERSEDID 
LEFT JOIN OAGWBG_V_EXT_OAGGL_DEPARTMENT_V DEPTV 
       ON BRS.DEPARTMENTID = DEPTV.ID
LEFT JOIN OAGWBG_V_EXT_OAGGL_COST_CENTER_V COSTV 
       ON BRS.COSTCENTERID = COSTV.ID
LEFT JOIN OAGWBG_V_SYSTEMUSER SU
       ON BRS.CREATEBY = SU.ID
LEFT JOIN OAGWBG_V_EXT_OAGPO_TRANSACTION_STATUS_V TSV
ON (
       BRSI.BUDGETRESERVEDTYPE IN ('R','EXPAND_PR')
   AND BRSI.BOOKNUMBER = TSV.PR_NUMBER
)
OR (
       BRSI.BUDGETRESERVEDTYPE IN ('O','EXPAND_PO')
   AND BRSI.BOOKNUMBER = TSV.PO_NUMBER
)
LEFT JOIN OAGWBG_V_BUDGETRECEIVE BR
ON BRSI.HEADERID = BR.ID
WHERE
     BRSI.STATUSID = 90102 OR   BRSI.STATUSID =90110 

/
