--------------------------------------------------------------------------------
-- ROLLBACK ALL — คืน view กลับเป็นฉบับก่อนแก้ (2026-08-27) ครบทั้ง 5 ตัว
--------------------------------------------------------------------------------
-- ⚠️ DDL ในไฟล์นี้ดึงมาจาก PREPROD (ebs_PRE) ก่อนแก้
--    ถ้าจะ rollback บน environment อื่น ให้ใช้ DDL ของ environment นั้นเอง :
--      SELECT TEXT FROM USER_VIEWS WHERE VIEW_NAME = '<ชื่อ view>';
--
-- ลำดับการรัน : V_BUDGETRESERVEDITEM ต้องมาก่อน (view อื่นพึ่งพามัน)
--------------------------------------------------------------------------------

SET DEFINE OFF
SET SQLBLANKLINES ON

PROMPT 1/5 : rollback OAGWBG_V_BUDGETRESERVEDITEM
CREATE OR REPLACE VIEW OAGWBG_V_BUDGETRESERVEDITEM AS
SELECT
    BR."ID",
    BR."CREATEBY",
    BR."CREATEON",
    BR."UPDATEBY",
    BR."UPDATEON",
    BR."BUDGETYEAR",
    BR."BUDGETREVERSEDID",
    BR."TOTALHASPOAMOUNT",
    BR."TOTALHASPRAMOUNT",
    BR."TOTALBALANCEAMOUNT",
    BR."BOOKNUMBER",
    BR."DESCRIPTION",
    BR."SUPPLIER",
    BR."COSTCENTERCODE",
    BR."HEADERID",
    BR."CATEGORYCODE",
    BR."ACCOUNTCODE",
    BR."STATUSID",
    CASE
        WHEN MS.NAME LIKE '%บันทึก%' THEN 'ส่งเรื่องให้พิจารณา'
        ELSE MS.NAME
    END AS STATUSNAME,
    BR."REASON",
    BB."BANKACCOUNTGIVER",
    BB."BANKACCOUNTRECEIVER",
    BS.COSTCENTERID,
    BS.DEPARTMENTID,
    BR.BUDGETRESERVEDTYPE,
    BR.PARENTID,
    BR.TRANSFERNO,
    BR.PO_CONTRACT,
    BR.PO_CONTRACT_START_DATE,
    BR.PO_CONTRACT_DUE_DATE,
    BR.OVERLAPYEAR,
    BR.OVERLAPROUND,
    BR.APPROVE,
    BR.REMAININGREFUND,
   COALESCE(BR.LINEID,BR1.LINEID) AS LINEID,
    --BR.LINEID AS LINEID,
    BR.NOTE,
    BR.USAGEAMOUNT,
    ovbr.PR_TRANSFER_NO AS PR_TRANSFER_NO,
    ovbo.PO_TRANSFER_NO AS PO_TRANSFER_NO,
    CFPO.PO_CONTRACT_DATE AS CONTRACT_CARRY_FORWARD_PO,
    BR.RESERVEDNO_ADD
FROM OAGWBG_BUDGETRESERVEDITEM BR
LEFT JOIN OAGWBG_BUDGETRESERVEDITEM BR1
	ON BR.PARENTID = BR1.ID
LEFT JOIN OAGWBG_MASTERSTATUS MS
       ON MS."ID" = BR."STATUSID"
LEFT JOIN OAGWBG_BUDGETRESERVED_BANKACCOUNT BB
       ON BR."BUDGETBANKACCOUNTID" = BB."ID"
LEFT JOIN OAGWBG_V_BUDGETRESERVED BS 
        ON BR.BUDGETREVERSEDID = BS.ID
LEFT JOIN (SELECT * FROM OAGWBG_V_EXT_OAGPO_TRANSACTION_STATUS_V a WHERE a.PR_TRANSFER_NO IS NOT NULL) ovbr
		ON ovbr.PR_BUDGET_ACCOUNT = BR.ACCOUNTCODE AND BR.BOOKNUMBER = ovbr.PR_NUMBER 
LEFT JOIN (SELECT * FROM OAGWBG_V_EXT_OAGPO_TRANSACTION_STATUS_V b WHERE b.PO_TRANSFER_NO IS NOT NULL) ovbo
		ON ovbo.PO_BUDGET_ACCOUNT = BR.ACCOUNTCODE AND BR.BOOKNUMBER = ovbo.PO_NUMBER 
LEFT JOIN APPS.OAGPO_TRANSACTION_STATUS_V CFPO
ON (
    CFPO.PR_BUDGET_ACCOUNT = BR.ACCOUNTCODE
    OR (
        CFPO.PO_BUDGET_ACCOUNT = BR.ACCOUNTCODE
        AND NOT EXISTS (
            SELECT 1
            FROM APPS.OAGPO_TRANSACTION_STATUS_V X
            WHERE X.PO_NUMBER = BR.BOOKNUMBER
              AND X.PO_LINE_ID = COALESCE(BR.LINEID, BR1.LINEID)
              AND X.PR_BUDGET_ACCOUNT = BR.ACCOUNTCODE
        )
    )
)
AND CFPO.PO_NUMBER = BR.BOOKNUMBER
AND CFPO.PO_LINE_ID = COALESCE(BR.LINEID, BR1.LINEID)



/

PROMPT 2/5 : rollback OAGWBG_R_BUDGETOVERLAP_CATEGORY
CREATE OR REPLACE VIEW OAGWBG_R_BUDGETOVERLAP_CATEGORY AS
SELECT
    BRS.ID                                   AS BUDGETRESERVEDID,
    CAT.BUDGETYEAR                           AS BUDGETYEAR,
    BRS.TRANSFERNO                           AS TRANSFERNO,
    BRS.RESERVATIONNAME                      AS RESERVATIONNAME,
    BRS.RESERVATIONTYPE                      AS RESERVATIONTYPE,
    BRS.BUDGETRESERVEDTYPE                   AS BUDGETRESERVEDTYPE,
    BRS.REASON                               AS REASON,
    BRS.CREATEON                             AS RESERVEDDATE,
    BRS.DEPARTMENTID                         AS DEPARTMENTID,
    DEPTV.NAME                               AS DEPARTMENTNAME,
    BRS.COSTCENTERID                         AS COSTCENTERID,
    COSTV.NAME                               AS COSTCENTERNAME,
    COSTV.REGIONID                           AS REGIONID,
    BRS.BUDGETRESERVEDREGION                 AS BUDGETRESERVEDREGION,

    -- ไม่มี item ในระดับหมวด
    CAST(NULL AS NUMBER)                     AS ITEMID,
    CAT.CATEGORYNAME                         AS DESCRIPTION,
    CAST(NULL AS VARCHAR2(240))              AS SUPPLIER,
    CAST(NULL AS VARCHAR2(50))               AS ITEMRESERVEDTYPE,
    CAST(NULL AS NUMBER)                     AS PRAMOUNT,
    CAST(NULL AS NUMBER)                     AS POAMOUNT,

    -- ยอดกันเงินก้อนแรกของหมวด
    CAT.TOTALRESERVEDAMOUNT                  AS TOTALBALANCEAMOUNT,

    CAST(NULL AS VARCHAR2(4000))             AS ITEMREASON,
    BRS.STATUSID                             AS STATUSID,
    CASE
        WHEN BRS.ROUNDINTERFACE = 1 THEN 'กันเงิน'
        WHEN BRS.ROUNDINTERFACE > 1 THEN 'ขยายระยะเวลา'
        ELSE 'ร่าง'
    END                                      AS STATUSNAME,
    BRS.CREATEON                             AS RESERVEDITEMDATE,
    TO_CHAR(BRS.CREATEON,'MM')               AS RESERVEDMONTH,
    CAST(NULL AS VARCHAR2(240))              AS PO_CONTRACT,
    CAST(NULL AS VARCHAR2(240))              AS PO_CONTRACT_DATE,
    CAST(NULL AS VARCHAR2(240))              AS PO_CONTRACT_START_DATE,
    CAST(NULL AS VARCHAR2(240))              AS PO_CONTRACT_DUE_DATE,
    CAST(NULL AS VARCHAR2(20))               AS BOOKNUMBER,
    CAST(NULL AS VARCHAR2(240))              AS COSTCENTERCODE,
    CAST(NULL AS VARCHAR2(337))              AS ACCOUNTCODE,
    BRS.BUDGETSOURCEID                       AS BUDGETSOURCEID,
    CAST(NULL AS VARCHAR2(1348))             AS BUDGETCODE,

    CAT.CATEGORYID                           AS CATEGORYID,
    CAT.CATEGORYNAME                         AS CATEGORYNAME,
    CAT.CATEGORY_CODE                        AS CATEGORY_CODE,
    CAT.TOTALRESERVEDAMOUNT                  AS TOTALRESERVEDAMOUNT,
    CAT.BUDGETPLANID                         AS BUDGETPLANID,
    CAT.PLAN_NAME                            AS PLAN_NAME,
    CAT.PRODUCTID                            AS PRODUCTID,
    CAT.PRODUCT_NAME                         AS PRODUCT_NAME,
    CAT.ACTIVITYID                           AS ACTIVITYID,
    CAT.ACTIVITY_NAME                        AS ACTIVITY_NAME,
    CAT.BUDGETCODEID                         AS BUDGETCODEID,

    -- ระดับหมวดไม่ผูกกับ PR/PO จึงระบุมีหนี้/ไม่มีหนี้ไม่ได้
    'ไม่ระบุ'                                AS RESERVEDTYPENAME,

    -- ผลพิจารณา : ส่วนกลางยึดสถานะของหัวกันเงิน
    CASE BRS.STATUSID
        WHEN 20202 THEN 'พิจารณาแล้ว'
        WHEN 90102 THEN 'ขยายเวลา'
        WHEN 90109 THEN 'ยกเลิก'
        WHEN 90110 THEN 'ยกเลิกการกันเงิน'
        WHEN 90101 THEN 'ปกติ'
        ELSE 'อื่น ๆ'
    END                                      AS RESERVEDSTATUSNAME,

    CAST(NULL AS VARCHAR2(240))              AS PR_STATUS,
    CAST(NULL AS VARCHAR2(240))              AS PO_STATUS
FROM       OAGWBG_V_BUDGETRESERVED          BRS
INNER JOIN (
    -- DISTINCT กันแถวซ้ำจากบั๊ก join BUDGETCODE_YEAR ใน view ต้นทาง
    SELECT DISTINCT
           BUDGETRESERVEDID, CATEGORYID, CATEGORYNAME, CATEGORY_CODE,
           BUDGETYEAR, TOTALRESERVEDAMOUNT, BUDGETPLANID, PLAN_NAME,
           PRODUCTID, PRODUCT_NAME, ACTIVITYID, ACTIVITY_NAME, BUDGETCODEID
    FROM   OAGWBG_V_BUDGETRESERVED_CATEGORY
)                                            CAT ON BRS.ID = CAT.BUDGETRESERVEDID
LEFT JOIN  OAGWBG_V_EXT_OAGGL_DEPARTMENT_V   DEPTV ON BRS.DEPARTMENTID = DEPTV.ID
LEFT JOIN  OAGWBG_V_EXT_OAGGL_COST_CENTER_V  COSTV ON BRS.COSTCENTERID = COSTV.ID
WHERE      BRS.BUDGETRESERVEDREGION = 'C'

UNION ALL

--==============================================================================
-- 2) ภูมิภาค : ระดับรายการ เฉพาะรายการที่กันเงินแล้ว
--==============================================================================
SELECT
    BRS.ID                                   AS BUDGETRESERVEDID,
    COALESCE(BRSI.BUDGETYEAR, BRS.BUDGETYEAR) AS BUDGETYEAR,
    BRS.TRANSFERNO                           AS TRANSFERNO,
    BRS.RESERVATIONNAME                      AS RESERVATIONNAME,
    BRS.RESERVATIONTYPE                      AS RESERVATIONTYPE,
    BRS.BUDGETRESERVEDTYPE                   AS BUDGETRESERVEDTYPE,
    BRS.REASON                               AS REASON,
    BRS.CREATEON                             AS RESERVEDDATE,
    BRS.DEPARTMENTID                         AS DEPARTMENTID,
    DEPTV.NAME                               AS DEPARTMENTNAME,
    BRS.COSTCENTERID                         AS COSTCENTERID,
    COSTV.NAME                               AS COSTCENTERNAME,
    COSTV.REGIONID                           AS REGIONID,
    BRS.BUDGETRESERVEDREGION                 AS BUDGETRESERVEDREGION,

    BRSI.ID                                  AS ITEMID,
    BRSI.DESCRIPTION                         AS DESCRIPTION,
    BRSI.SUPPLIER                            AS SUPPLIER,
    BRSI.BUDGETRESERVEDTYPE                  AS ITEMRESERVEDTYPE,
    BRSI.TOTALHASPRAMOUNT                    AS PRAMOUNT,
    BRSI.TOTALHASPOAMOUNT                    AS POAMOUNT,
    BRSI.TOTALBALANCEAMOUNT                  AS TOTALBALANCEAMOUNT,
    BRSI.REASON                              AS ITEMREASON,
    BRSI.STATUSID                            AS STATUSID,
    CASE
        WHEN BRS.ROUNDINTERFACE = 1 THEN 'กันเงิน'
        WHEN BRS.ROUNDINTERFACE > 1 THEN 'ขยายระยะเวลา'
        ELSE 'ร่าง'
    END                                      AS STATUSNAME,
    BRSI.CREATEON                            AS RESERVEDITEMDATE,
    TO_CHAR(BRSI.CREATEON,'MM')              AS RESERVEDMONTH,
    BRSI.PO_CONTRACT                         AS PO_CONTRACT,
    BRSI.CONTRACT_CARRY_FORWARD_PO           AS PO_CONTRACT_DATE,
    BRSI.PO_CONTRACT_START_DATE              AS PO_CONTRACT_START_DATE,
    BRSI.PO_CONTRACT_DUE_DATE                AS PO_CONTRACT_DUE_DATE,
    BRSI.BOOKNUMBER                          AS BOOKNUMBER,
    BRSI.COSTCENTERCODE                      AS COSTCENTERCODE,
    BRSI.ACCOUNTCODE                         AS ACCOUNTCODE,
    CASE
        WHEN BRS.BUDGETRESERVEDREGION = 'P' AND BRSI.ACCOUNTCODE IS NOT NULL
             THEN REGEXP_SUBSTR(BRSI.ACCOUNTCODE, '[^.]+', 1, 4)
        ELSE BRS.BUDGETSOURCEID
    END                                      AS BUDGETSOURCEID,
    REGEXP_SUBSTR(BRSI.ACCOUNTCODE, '[^.]+', 1, 9) AS BUDGETCODE,

    CAST(NULL AS NUMBER)                     AS CATEGORYID,
    CAST(NULL AS VARCHAR2(240))              AS CATEGORYNAME,
    CAST(NULL AS VARCHAR2(240))              AS CATEGORY_CODE,
    CAST(NULL AS NUMBER)                     AS TOTALRESERVEDAMOUNT,
    CAST(NULL AS VARCHAR2(240))              AS BUDGETPLANID,
    CAST(NULL AS VARCHAR2(240))              AS PLAN_NAME,
    CAST(NULL AS VARCHAR2(240))              AS PRODUCTID,
    CAST(NULL AS VARCHAR2(240))              AS PRODUCT_NAME,
    CAST(NULL AS VARCHAR2(240))              AS ACTIVITYID,
    CAST(NULL AS VARCHAR2(240))              AS ACTIVITY_NAME,
    CAST(NULL AS VARCHAR2(240))              AS BUDGETCODEID,

    CASE
        WHEN BRSI.BUDGETRESERVEDTYPE = 'O' THEN 'มีหนี้'
        WHEN BRSI.BUDGETRESERVEDTYPE = 'R' THEN 'ไม่มีหนี้'
        ELSE 'ไม่ระบุ'
    END                                      AS RESERVEDTYPENAME,

    -- ผลพิจารณา : ภูมิภาคยึดสถานะของรายการ
    CASE BRSI.STATUSID
        WHEN 20202 THEN 'พิจารณาแล้ว'
        WHEN 90102 THEN 'ขยายเวลา'
        WHEN 90109 THEN 'ยกเลิก'
        WHEN 90110 THEN 'ยกเลิกการกันเงิน'
        WHEN 90101 THEN 'ปกติ'
        ELSE 'อื่น ๆ'
    END                                      AS RESERVEDSTATUSNAME,

    TSV.PR_STATUS                            AS PR_STATUS,
    TSV.PO_STATUS                            AS PO_STATUS
FROM       OAGWBG_V_BUDGETRESERVED          BRS
INNER JOIN OAGWBG_V_BUDGETRESERVEDITEM      BRSI  ON BRS.ID = BRSI.BUDGETREVERSEDID
LEFT JOIN  OAGWBG_V_EXT_OAGGL_DEPARTMENT_V  DEPTV ON BRS.DEPARTMENTID = DEPTV.ID
LEFT JOIN  OAGWBG_V_EXT_OAGGL_COST_CENTER_V COSTV ON BRS.COSTCENTERID = COSTV.ID
LEFT JOIN (
    SELECT PR_BUDGET_ACCOUNT, PO_BUDGET_ACCOUNT,
           MAX(PR_STATUS) AS PR_STATUS,
           MAX(PO_STATUS) AS PO_STATUS
    FROM   OAGWBG_V_EXT_OAGPO_TRANSACTION_STATUS_V
    GROUP BY PR_BUDGET_ACCOUNT, PO_BUDGET_ACCOUNT
)                                            TSV ON BRSI.ACCOUNTCODE = TSV.PR_BUDGET_ACCOUNT
                                                AND BRSI.ACCOUNTCODE = TSV.PO_BUDGET_ACCOUNT
WHERE      BRS.BUDGETRESERVEDREGION <> 'C'
       AND BRSI.BUDGETRESERVEDTYPE IN ('O','R')



/

PROMPT 3/5 : rollback OAGWBG_R_BUDGETOVERLAP_EXPAND
CREATE OR REPLACE VIEW OAGWBG_R_BUDGETOVERLAP_EXPAND AS
SELECT
    -- ข้อมูลหลักจากหัวกันเงิน
    BRS.ID AS BUDGETRESERVEDID,
    COALESCE(BRSI.BUDGETYEAR, BRS.BUDGETYEAR) AS BUDGETYEAR,
    BRS.TRANSFERNO,
    BRS.RESERVATIONNAME,
    BRS.RESERVATIONTYPE,
    BRS.BUDGETRESERVEDTYPE,
    SU.DEPARTMENTID AS DEPARTMENTID_CREATER,
    SU.DEPARTMENTNAME AS DEPARTMENTNAME_CREATER,
    SU.COSTCENTERID AS COSTCENTERID_CREATER,
    SU.COSTCENTERNAME AS COSTCENTERNAME_CREATER,
    BRS.REASON,
    BRS.CREATEON AS RESERVEDDATE,
    BRS.DEPARTMENTID,
    DEPTV.NAME AS DEPARTMENTNAME,
    BRS.COSTCENTERID,
    COSTV.NAME AS COSTCENTERNAME,
    COSTV.REGIONID,
    BRS.BUDGETRESERVEDREGION ,
    
    -- ข้อมูลจากรายการกันเงิน (Item)
    BRSI.ID AS ITEMID,
    CASE WHEN  BRSI.BUDGETRESERVEDTYPE = 'EXPAND_LUMP' OR BRSI.BUDGETRESERVEDTYPE = 'CANCEL_LUMP' THEN  BR.CATEGORYNAME 
    ELSE BRSI.DESCRIPTION END AS DESCRIPTION,
    BRSI.SUPPLIER,
    BRSI.BUDGETRESERVEDTYPE AS ITEMRESERVEDTYPE,
    BRSI.TOTALHASPRAMOUNT AS PRAMOUNT,
    CASE WHEN  BRSI.BUDGETRESERVEDTYPE = 'EXPAND_LUMP' OR BRSI.BUDGETRESERVEDTYPE = 'CANCEL_LUMP' THEN BRSI.USAGEAMOUNT
    ELSE BRSI.TOTALHASPOAMOUNT END AS POAMOUNT, 
    
    BRSI.REASON AS ITEMREASON,
    CASE 
      WHEN BRS.BUDGETRESERVEDREGION = 'C' THEN BRSI.STATUSID
      ELSE BRS.STATUSID
    END AS STATUSID,
--    CASE 
--      WHEN BRS.BUDGETRESERVEDREGION = 'C' THEN BRSI.STATUSNAME
--      ELSE BRS.STATUSNAME
--    END AS STATUSNAME,
    CASE
            WHEN BRS.ROUNDINTERFACE = 1 THEN 'กันเงิน'
            WHEN BRS.ROUNDINTERFACE > 1 THEN 'ขยายระยะเวลา'
            ELSE 'ร่าง'
    END AS STATUSNAME ,
    
    BRSI.CREATEON AS RESERVEDITEMDATE,
    TO_CHAR(BRSI.CREATEON,'MM') AS RESERVEDMONTH,
    BRSI.PO_CONTRACT,
    BRSI.PO_CONTRACT_START_DATE,
    BRSI.PO_CONTRACT_DUE_DATE,
    BRSI.BOOKNUMBER,
    BRSI.COSTCENTERCODE,
    BRSI.ACCOUNTCODE,

    -- ดึงรหัส segment ที่จำเป็น 
    CASE BUDGETRESERVEDREGION
            WHEN 'C' THEN REGEXP_SUBSTR(BRSI.ACCOUNTCODE, '[^.]+', 1, 4)
            WHEN 'P' THEN REGEXP_SUBSTR(BRSI.ACCOUNTCODE, '[^.]+', 1, 4)
            ELSE BRS.BUDGETSOURCEID
    END AS BUDGETSOURCEID,
    
    REGEXP_SUBSTR(BRSI.ACCOUNTCODE, '[^.]+', 1, 9) AS BUDGETCODE,


    -- แปลงประเภทการกันเงิน (เพิ่มเรื่องขยายเวลาแล้ว)
    CASE
         WHEN BRSI.BUDGETRESERVEDTYPE = 'O' THEN 'มีหนี้'
         WHEN BRSI.BUDGETRESERVEDTYPE = 'R' THEN 'ไม่มีหนี้'
         WHEN BRSI.BUDGETRESERVEDTYPE = 'EXPAND_PO' THEN 'มีหนี้'
         WHEN BRSI.BUDGETRESERVEDTYPE = 'EXPAND_PR' THEN 'ไม่มีหนี้'
         WHEN BRSI.BUDGETRESERVEDTYPE = 'CANCEL_PO' THEN 'มีหนี้'
         WHEN BRSI.BUDGETRESERVEDTYPE = 'CANCEL_PR' THEN 'ไม่มีหนี้'
         WHEN BRSI.BUDGETRESERVEDTYPE = 'EXPAND_LUMP' THEN 'ไม่มีหนี้'
         WHEN BRSI.BUDGETRESERVEDTYPE = 'CANCEL_LUMP' THEN 'ไม่มีหนี้'
        ELSE 'ไม่ระบุ'
    END AS RESERVEDTYPENAME,

    -- แสดงสถานะรายการตาม StatusId
          CASE
              WHEN (CASE WHEN BRS.BUDGETRESERVEDREGION = 'C' THEN BRS.STATUSID ELSE BRSI.STATUSID END) = 90102 THEN 'ขยายเวลา'
              WHEN (CASE WHEN BRS.BUDGETRESERVEDREGION = 'C' THEN BRS.STATUSID ELSE BRSI.STATUSID END) = 90109 THEN 'ยกเลิก'
              WHEN (CASE WHEN BRS.BUDGETRESERVEDREGION = 'C' THEN BRS.STATUSID ELSE BRSI.STATUSID END) = 90101 THEN 'ปกติ'
               WHEN (CASE WHEN BRS.BUDGETRESERVEDREGION = 'C' THEN BRS.STATUSID ELSE BRSI.STATUSID END) = 20202 THEN 'พิจารณาแล้ว'
              ELSE 'อื่น ๆ'
          END AS RESERVEDSTATUSNAME,

    -- ใช้ใน Template 2: รายงานขยายเวลา
          CASE
              WHEN (CASE WHEN BRS.BUDGETRESERVEDREGION = 'C' THEN BRS.STATUSID ELSE BRSI.STATUSID END) = 90102 
              THEN 'ขยาย(กันต่อ)'
              ELSE NULL
          END AS EXTENSIONSTATUS,
          
    -- สถานะ PR/PO
        CASE
            WHEN BRSI.BUDGETRESERVEDTYPE IN ('R','EXPAND_PR')
            THEN TSV.PR_STATUS
        END AS PR_STATUS,
        
        CASE
            WHEN BRSI.BUDGETRESERVEDTYPE IN ('O','EXPAND_PO')
            THEN TSV.PO_STATUS
        END AS PO_STATUS,
   BRSI.CONTRACT_CARRY_FORWARD_PO AS CONTRACT_CARRY_FORWARD_PO,
   BRSI.RESERVEDNO_ADD,
   BRSI.OVERLAPROUND
FROM OAGWBG_V_BUDGETRESERVED BRS 
LEFT JOIN OAGWBG_V_BUDGETRESERVEDITEM BRSI
       ON BRS.ID = BRSI.BUDGETREVERSEDID 
LEFT JOIN OAGWBG_V_EXT_OAGGL_DEPARTMENT_V DEPTV 
       ON BRS.DEPARTMENTID = DEPTV.ID
LEFT JOIN OAGWBG_V_EXT_OAGGL_COST_CENTER_V COSTV 
       ON BRS.COSTCENTERID = COSTV.ID
LEFT JOIN OAGWBG_V_SYSTEMUSER SU
       ON BRS.CREATEBY = SU.ID
LEFT JOIN OAGWBG_V_EXT_OAGPO_TRANSACTION_STATUS_V TSV
ON (
       BRSI.BUDGETRESERVEDTYPE IN ('R','EXPAND_PR')
   AND BRSI.BOOKNUMBER = TSV.PR_NUMBER
)
OR (
       BRSI.BUDGETRESERVEDTYPE IN ('O','EXPAND_PO')
   AND BRSI.BOOKNUMBER = TSV.PO_NUMBER
)
LEFT JOIN OAGWBG_V_BUDGETRECEIVE BR
ON BRSI.HEADERID = BR.ID
WHERE
     BRSI.STATUSID = 90102 OR   BRSI.STATUSID =90110 



/

PROMPT 4/5 : rollback OAGWBG_R_BUDGETOVERLAP
CREATE OR REPLACE VIEW OAGWBG_R_BUDGETOVERLAP AS
SELECT
    BRS.ID AS BUDGETRESERVEDID,
    COALESCE(CAT.BUDGETYEAR, BRSI.BUDGETYEAR, BRS.BUDGETYEAR) AS BUDGETYEAR,
    BRS.TRANSFERNO,
    BRS.RESERVATIONNAME,
    BRS.RESERVATIONTYPE,
    BRS.BUDGETRESERVEDTYPE,
    BRS.REASON,
    BRS.CREATEON AS RESERVEDDATE,
    BRS.DEPARTMENTID,
    DEPTV.NAME AS DEPARTMENTNAME,
    BRS.COSTCENTERID,
    COSTV.NAME AS COSTCENTERNAME,
    COSTV.REGIONID,
    BRS.BUDGETRESERVEDREGION,
    BRSI.ID AS ITEMID,
    BRSI.DESCRIPTION,
    BRSI.SUPPLIER,
    BRSI.BUDGETRESERVEDTYPE AS ITEMRESERVEDTYPE,
    BRSI.TOTALHASPRAMOUNT AS PRAMOUNT,
    BRSI.TOTALHASPOAMOUNT AS POAMOUNT,
    CASE 
        WHEN BUDGETRESERVEDREGION = 'C' THEN CAT.TOTALRESERVEDAMOUNT
        ELSE BRSI.TOTALBALANCEAMOUNT
    END AS TOTALBALANCEAMOUNT,
    BRSI.REASON AS ITEMREASON,
    CASE 
        WHEN BRS.BUDGETRESERVEDREGION = 'C' OR BRS.BUDGETRESERVEDREGION = 'P'  THEN BRS.STATUSID
        ELSE BRSI.STATUSID
    END AS STATUSID,
--    CASE 
--        WHEN BRS.BUDGETRESERVEDREGION = 'C' OR BRS.BUDGETRESERVEDREGION = 'P' THEN BRS.STATUSNAME
--        ELSE BRSI.STATUSNAME
--    END AS STATUSNAME,
    CASE
            WHEN BRS.ROUNDINTERFACE = 1 THEN 'กันเงิน'
            WHEN BRS.ROUNDINTERFACE > 1 THEN 'ขยายระยะเวลา'
            ELSE 'ร่าง'
    END AS STATUSNAME,
    BRSI.CREATEON AS RESERVEDITEMDATE,
    TO_CHAR(BRSI.CREATEON,'MM') AS RESERVEDMONTH,
    BRSI.PO_CONTRACT,
    BRSI.CONTRACT_CARRY_FORWARD_PO  AS PO_CONTRACT_DATE,
    BRSI.PO_CONTRACT_START_DATE,
    BRSI.PO_CONTRACT_DUE_DATE,
    BRSI.BOOKNUMBER,
    BRSI.COSTCENTERCODE,
    BRSI.ACCOUNTCODE,
    CASE 
        WHEN BUDGETRESERVEDREGION = 'C' AND BRSI.ACCOUNTCODE IS NOT NULL THEN  REGEXP_SUBSTR(BRSI.ACCOUNTCODE, '[^.]+', 1, 4)
        WHEN BUDGETRESERVEDREGION = 'P' AND BRSI.ACCOUNTCODE IS NOT NULL THEN  REGEXP_SUBSTR(BRSI.ACCOUNTCODE, '[^.]+', 1, 4)
        ELSE BRS.BUDGETSOURCEID
    END AS BUDGETSOURCEID,
    REGEXP_SUBSTR(BRSI.ACCOUNTCODE, '[^.]+', 1, 9) AS BUDGETCODE,
    CAT.CATEGORYID,
    CAT.CATEGORYNAME,
    CAT.CATEGORY_CODE,
    CAT.TOTALRESERVEDAMOUNT,
    CAT.BUDGETPLANID,
    CAT.PLAN_NAME,
    CAT.PRODUCTID,
    CAT.PRODUCT_NAME,
    CAT.ACTIVITYID,
    CAT.ACTIVITY_NAME,
    CAT.BUDGETCODEID,
    CASE
        WHEN BRSI.BUDGETRESERVEDTYPE = 'O' THEN 'มีหนี้'
        WHEN BRSI.BUDGETRESERVEDTYPE = 'R' THEN 'ไม่มีหนี้'
        WHEN BRSI.BUDGETRESERVEDTYPE = 'EXPAND_PO' THEN 'มีหนี้'
        WHEN BRSI.BUDGETRESERVEDTYPE = 'EXPAND_PR' THEN 'ไม่มีหนี้'
        ELSE 'ไม่ระบุ'
    END AS RESERVEDTYPENAME,
     CASE
              WHEN (CASE WHEN BRS.BUDGETRESERVEDREGION = 'C' THEN BRS.STATUSID ELSE BRSI.STATUSID END) = 90102 THEN 'ขยายเวลา'
              WHEN (CASE WHEN BRS.BUDGETRESERVEDREGION = 'C' THEN BRS.STATUSID ELSE BRSI.STATUSID END) = 90109 THEN 'ยกเลิก'
              WHEN (CASE WHEN BRS.BUDGETRESERVEDREGION = 'C' THEN BRS.STATUSID ELSE BRSI.STATUSID END) = 90101 THEN 'ปกติ'
               WHEN (CASE WHEN BRS.BUDGETRESERVEDREGION = 'C' THEN BRS.STATUSID ELSE BRSI.STATUSID END) = 20202 THEN 'พิจารณาแล้ว'
              ELSE 'อื่น ๆ'
          END AS RESERVEDSTATUSNAME,
    TSV.PR_STATUS,
    TSV.PO_STATUS
FROM OAGWBG_V_BUDGETRESERVED BRS 
LEFT JOIN OAGWBG_V_BUDGETRESERVEDITEM BRSI
       ON BRS.ID = BRSI.BUDGETREVERSEDID
LEFT JOIN OAGWBG_V_BUDGETRESERVED_CATEGORY CAT 
       ON BRS.ID = CAT.BUDGETRESERVEDID
LEFT JOIN OAGWBG_V_EXT_OAGGL_DEPARTMENT_V DEPTV 
       ON BRS.DEPARTMENTID = DEPTV.ID
LEFT JOIN OAGWBG_V_EXT_OAGGL_COST_CENTER_V COSTV 
       ON BRS.COSTCENTERID = COSTV.ID
LEFT JOIN (
    SELECT PR_BUDGET_ACCOUNT, PO_BUDGET_ACCOUNT,
           MAX(PR_STATUS) AS PR_STATUS,
           MAX(PO_STATUS) AS PO_STATUS
    FROM OAGWBG_V_EXT_OAGPO_TRANSACTION_STATUS_V
    GROUP BY PR_BUDGET_ACCOUNT, PO_BUDGET_ACCOUNT
) TSV ON BRSI.ACCOUNTCODE = TSV.PR_BUDGET_ACCOUNT
     AND BRSI.ACCOUNTCODE = TSV.PO_BUDGET_ACCOUNT



/

PROMPT 5/5 : rollback OAGWBG_R_BUDGETOVERLAP_RESERVED
CREATE OR REPLACE VIEW OAGWBG_R_BUDGETOVERLAP_RESERVED AS
SELECT
    -- ===== ระดับหัวกันเงิน (group) =====
    BRS.ID                                   AS BUDGETRESERVEDID,
    BRSI.BUDGETYEAR                           AS BUDGETYEAR,
    BRS.TRANSFERNO                           AS TRANSFERNO,            -- เลขที่กันเงิน (หัวกลุ่มรายงาน)
    BRS.RESERVATIONNAME                      AS RESERVATIONNAME,
    BRS.RESERVATIONTYPE                      AS RESERVATIONTYPE,
    BRS.BUDGETRESERVEDREGION                 AS BUDGETRESERVEDREGION,

    -- ===== เลขที่โอนจัดสรร (?? ดูข้อ 7.1) =====
    COALESCE(BRSI.PO_TRANSFER_NO, BRSI.PR_TRANSFER_NO, BRSI.TRANSFERNO) AS ALLOCATE_TRANSFERNO,

    -- ===== พื้นที่ภาค / สำนักงาน (จากศูนย์ต้นทุน) =====
    COSTV.REGIONID                           AS REGIONID,
    COSTV.REGIONNAME                         AS REGIONNAME,            -- พื้นที่ ภาค
    BRS.COSTCENTERID                         AS COSTCENTERID,
    COSTV.NAME                               AS COSTCENTERNAME,        -- สำนักงาน
    BRS.DEPARTMENTID                         AS DEPARTMENTID,
    DEPTV.NAME                               AS DEPARTMENTNAME,

    -- ===== รายการ (หมวด) =====
    CAT.CATEGORYID                           AS CATEGORYID,
    CAT.CATEGORYNAME                         AS CATEGORYNAME,          -- รายการ (ตาม prompt)
    CAT.CATEGORY_CODE                        AS CATEGORY_CODE,
    CAT.TOTALRESERVEDAMOUNT                  AS TOTALRESERVEDAMOUNT,   -- ยอดกันเงินรวมของหมวด

    -- ===== ระดับรายการ (item) =====
    BRSI.ID                                  AS ITEMID,
    BRSI.DESCRIPTION                         AS DESCRIPTION,           -- ชื่อรายการระดับ item (ที่ PDF โชว์ในบรรทัดย่อย)
    BRSI.SUPPLIER                            AS SUPPLIER,
    BRSI.BOOKNUMBER                          AS BOOKNUMBER,            -- เลขที่เอกสาร
    BRSI.ACCOUNTCODE                         AS ACCOUNTCODE,
    BRSI.BUDGETRESERVEDTYPE                  AS ITEMRESERVEDTYPE,      -- O/R/EXPAND_*/CANCEL_*
    BRSI.TOTALBALANCEAMOUNT                  AS TOTALBALANCEAMOUNT,    -- จำนวนเงินจัดสรร
    BRSI.USAGEAMOUNT                         AS USAGEAMOUNT,           -- ยอดที่ใช้ (raw)
    BRSI.RESERVEDNO_ADD                      AS RESERVEDNO_ADD,        -- เลขที่เงินกันเพิ่ม .n
    BRSI.NOTE                                AS NOTE,                  -- หมายเหตุ
    BRSI.OVERLAPYEAR                         AS OVERLAPYEAR,
    BRSI.OVERLAPROUND                        AS OVERLAPROUND,
    BRSI.CREATEON                            AS RESERVEDITEMDATE,

    -- ===== pivot ยอดตามประเภท (คอลัมน์รายงานตรง ๆ) =====
    CASE WHEN BRSI.BUDGETRESERVEDTYPE = 'EXPAND_PO' THEN BRSI.USAGEAMOUNT END AS APPROVE_EXPAND_HASOBLIGATION,  -- อนุมัติขยาย: มีหนี้
    CASE WHEN BRSI.BUDGETRESERVEDTYPE = 'EXPAND_PR' THEN BRSI.USAGEAMOUNT END AS APPROVE_EXPAND_NOOBLIGATION,   -- อนุมัติขยาย: ไม่มีหนี้
    CASE WHEN BRSI.BUDGETRESERVEDTYPE = 'CANCEL_PO' THEN BRSI.USAGEAMOUNT END AS PROCESS_HASOBLIGATION,         -- ดำเนินการ: มีหนี้
    CASE WHEN BRSI.BUDGETRESERVEDTYPE = 'CANCEL_PR' THEN BRSI.USAGEAMOUNT END AS PROCESS_NOOBLIGATION,          -- ดำเนินการ: ไม่มีหนี้

    -- ===== แปลประเภท / สถานะ (สไตล์เดียวกับวิวเดิม) =====
    CASE
        WHEN BRSI.BUDGETRESERVEDTYPE IN ('O','EXPAND_PO','CANCEL_PO') THEN 'มีหนี้'
        WHEN BRSI.BUDGETRESERVEDTYPE IN ('R','EXPAND_PR','CANCEL_PR') THEN 'ไม่มีหนี้'
        ELSE 'ไม่ระบุ'
    END                                      AS RESERVEDTYPENAME,
    CASE WHEN BRS.BUDGETRESERVEDREGION = 'C' THEN BRS.STATUSID   ELSE BRSI.STATUSID   END AS STATUSID,
    CASE WHEN BRS.BUDGETRESERVEDREGION = 'C' THEN BRS.STATUSNAME ELSE BRSI.STATUSNAME END AS STATUSNAME
FROM       OAGWBG_V_BUDGETRESERVED           BRS
LEFT JOIN  OAGWBG_V_BUDGETRESERVEDITEM       BRSI  ON BRS.ID = BRSI.BUDGETREVERSEDID AND (BRSI.PO_TRANSFER_NO IS NOT NULL OR BRSI.PR_TRANSFER_NO IS NOT NULL)
LEFT JOIN  OAGWBG_V_BUDGETRESERVED_CATEGORY  CAT   ON BRS.ID = CAT.BUDGETRESERVEDID   -- ?? ดูข้อ 7.2 (1 หมวด/หัว)
LEFT JOIN  OAGWBG_V_EXT_OAGGL_DEPARTMENT_V   DEPTV ON BRS.DEPARTMENTID = DEPTV.ID
LEFT JOIN  OAGWBG_V_EXT_OAGGL_COST_CENTER_V  COSTV ON BRS.COSTCENTERID = COSTV.ID
WHERE  BRSI.BUDGETRESERVEDTYPE IN ('EXPAND_PO','EXPAND_PR','CANCEL_PO','CANCEL_PR')  




/

PROMPT ตรวจผลลัพธ์ — ต้อง VALID ทุกตัว
SELECT OBJECT_NAME, STATUS
FROM   USER_OBJECTS
WHERE  OBJECT_NAME IN ('OAGWBG_V_BUDGETRESERVEDITEM',
                       'OAGWBG_R_BUDGETOVERLAP_CATEGORY',
                       'OAGWBG_R_BUDGETOVERLAP_EXPAND',
                       'OAGWBG_R_BUDGETOVERLAP',
                       'OAGWBG_R_BUDGETOVERLAP_RESERVED')
ORDER BY OBJECT_NAME;
