CREATE OR REPLACE VIEW OAGWBG_R_BUDGETOVERLAP AS
SELECT
    BRS.ID AS BUDGETRESERVEDID,
    COALESCE(CAT.BUDGETYEAR, BRSI.BUDGETYEAR, BRS.BUDGETYEAR) AS BUDGETYEAR,
    BRS.TRANSFERNO,
    BRS.RESERVATIONNAME,
    BRS.RESERVATIONTYPE,
    BRS.BUDGETRESERVEDTYPE,
    BRS.REASON,
    BRS.CREATEON AS RESERVEDDATE,
    BRS.DEPARTMENTID,
    DEPTV.NAME AS DEPARTMENTNAME,
    BRS.COSTCENTERID,
    COSTV.NAME AS COSTCENTERNAME,
    COSTV.REGIONID,
    BRS.BUDGETRESERVEDREGION,
    BRSI.ID AS ITEMID,
    BRSI.DESCRIPTION,
    BRSI.SUPPLIER,
    BRSI.BUDGETRESERVEDTYPE AS ITEMRESERVEDTYPE,
    BRSI.TOTALHASPRAMOUNT AS PRAMOUNT,
    BRSI.TOTALHASPOAMOUNT AS POAMOUNT,
    CASE 
        WHEN BUDGETRESERVEDREGION = 'C' THEN CAT.TOTALRESERVEDAMOUNT
        ELSE BRSI.TOTALBALANCEAMOUNT
    END AS TOTALBALANCEAMOUNT,
    BRSI.REASON AS ITEMREASON,
    CASE 
        WHEN BRS.BUDGETRESERVEDREGION = 'C' OR BRS.BUDGETRESERVEDREGION = 'P'  THEN BRS.STATUSID
        ELSE BRSI.STATUSID
    END AS STATUSID,
--    CASE 
--        WHEN BRS.BUDGETRESERVEDREGION = 'C' OR BRS.BUDGETRESERVEDREGION = 'P' THEN BRS.STATUSNAME
--        ELSE BRSI.STATUSNAME
--    END AS STATUSNAME,
    CASE
            WHEN BRS.ROUNDINTERFACE = 1 THEN 'กันเงิน'
            WHEN BRS.ROUNDINTERFACE > 1 THEN 'ขยายระยะเวลา'
            ELSE 'ร่าง'
    END AS STATUSNAME,
    BRSI.CREATEON AS RESERVEDITEMDATE,
    TO_CHAR(BRSI.CREATEON,'MM') AS RESERVEDMONTH,
    BRSI.PO_CONTRACT,
    BRSI.CONTRACT_CARRY_FORWARD_PO  AS PO_CONTRACT_DATE,
    BRSI.PO_CONTRACT_START_DATE,
    BRSI.PO_CONTRACT_DUE_DATE,
    BRSI.BOOKNUMBER,
    BRSI.COSTCENTERCODE,
    BRSI.ACCOUNTCODE,
    CASE 
        WHEN BUDGETRESERVEDREGION = 'C' AND BRSI.ACCOUNTCODE IS NOT NULL THEN  REGEXP_SUBSTR(BRSI.ACCOUNTCODE, '[^.]+', 1, 4)
        WHEN BUDGETRESERVEDREGION = 'P' AND BRSI.ACCOUNTCODE IS NOT NULL THEN  REGEXP_SUBSTR(BRSI.ACCOUNTCODE, '[^.]+', 1, 4)
        ELSE BRS.BUDGETSOURCEID
    END AS BUDGETSOURCEID,
    REGEXP_SUBSTR(BRSI.ACCOUNTCODE, '[^.]+', 1, 9) AS BUDGETCODE,
    CAT.CATEGORYID,
    CAT.CATEGORYNAME,
    CAT.CATEGORY_CODE,
    CAT.TOTALRESERVEDAMOUNT,
    CAT.BUDGETPLANID,
    CAT.PLAN_NAME,
    CAT.PRODUCTID,
    CAT.PRODUCT_NAME,
    CAT.ACTIVITYID,
    CAT.ACTIVITY_NAME,
    CAT.BUDGETCODEID,
    CASE
        WHEN BRSI.BUDGETRESERVEDTYPE = 'O' THEN 'มีหนี้'
        WHEN BRSI.BUDGETRESERVEDTYPE = 'R' THEN 'ไม่มีหนี้'
        WHEN BRSI.BUDGETRESERVEDTYPE = 'EXPAND_PO' THEN 'มีหนี้'
        WHEN BRSI.BUDGETRESERVEDTYPE = 'EXPAND_PR' THEN 'ไม่มีหนี้'
        ELSE 'ไม่ระบุ'
    END AS RESERVEDTYPENAME,
     CASE
              WHEN (CASE WHEN BRS.BUDGETRESERVEDREGION = 'C' THEN BRS.STATUSID ELSE BRSI.STATUSID END) = 90102 THEN 'ขยายเวลา'
              WHEN (CASE WHEN BRS.BUDGETRESERVEDREGION = 'C' THEN BRS.STATUSID ELSE BRSI.STATUSID END) = 90109 THEN 'ยกเลิก'
              WHEN (CASE WHEN BRS.BUDGETRESERVEDREGION = 'C' THEN BRS.STATUSID ELSE BRSI.STATUSID END) = 90101 THEN 'ปกติ'
               WHEN (CASE WHEN BRS.BUDGETRESERVEDREGION = 'C' THEN BRS.STATUSID ELSE BRSI.STATUSID END) = 20202 THEN 'พิจารณาแล้ว'
              ELSE 'อื่น ๆ'
          END AS RESERVEDSTATUSNAME,
    TSV.PR_STATUS,
    TSV.PO_STATUS
FROM OAGWBG_V_BUDGETRESERVED BRS 
LEFT JOIN OAGWBG_V_BUDGETRESERVEDITEM BRSI
       ON BRS.ID = BRSI.BUDGETREVERSEDID
LEFT JOIN OAGWBG_V_BUDGETRESERVED_CATEGORY CAT 
       ON BRS.ID = CAT.BUDGETRESERVEDID
LEFT JOIN OAGWBG_V_EXT_OAGGL_DEPARTMENT_V DEPTV 
       ON BRS.DEPARTMENTID = DEPTV.ID
LEFT JOIN OAGWBG_V_EXT_OAGGL_COST_CENTER_V COSTV 
       ON BRS.COSTCENTERID = COSTV.ID
LEFT JOIN (
    SELECT PR_BUDGET_ACCOUNT, PO_BUDGET_ACCOUNT,
           MAX(PR_STATUS) AS PR_STATUS,
           MAX(PO_STATUS) AS PO_STATUS
    FROM OAGWBG_V_EXT_OAGPO_TRANSACTION_STATUS_V
    GROUP BY PR_BUDGET_ACCOUNT, PO_BUDGET_ACCOUNT
) TSV ON BRSI.ACCOUNTCODE = TSV.PR_BUDGET_ACCOUNT
     AND BRSI.ACCOUNTCODE = TSV.PO_BUDGET_ACCOUNT

/
