CREATE OR REPLACE VIEW OAGWBG_V_BUDGETRESERVEDITEM AS
SELECT
    BR."ID",
    BR."CREATEBY",
    BR."CREATEON",
    BR."UPDATEBY",
    BR."UPDATEON",
    BR."BUDGETYEAR",
    BR."BUDGETREVERSEDID",
    BR."TOTALHASPOAMOUNT",
    BR."TOTALHASPRAMOUNT",
    BR."TOTALBALANCEAMOUNT",
    BR."BOOKNUMBER",
    BR."DESCRIPTION",
    BR."SUPPLIER",
    BR."COSTCENTERCODE",
    BR."HEADERID",
    BR."CATEGORYCODE",
    BR."ACCOUNTCODE",
    BR."STATUSID",
    CASE
        WHEN MS.NAME LIKE '%บันทึก%' THEN 'ส่งเรื่องให้พิจารณา'
        ELSE MS.NAME
    END AS STATUSNAME,
    BR."REASON",
    BB."BANKACCOUNTGIVER",
    BB."BANKACCOUNTRECEIVER",
    BS.COSTCENTERID,
    BS.DEPARTMENTID,
    BR.BUDGETRESERVEDTYPE,
    BR.PARENTID,
    BR.TRANSFERNO,
    BR.PO_CONTRACT,
    BR.PO_CONTRACT_START_DATE,
    BR.PO_CONTRACT_DUE_DATE,
    BR.OVERLAPYEAR,
    BR.OVERLAPROUND,
    BR.APPROVE,
    BR.REMAININGREFUND,
   COALESCE(BR.LINEID,BR1.LINEID) AS LINEID,
    --BR.LINEID AS LINEID,
    BR.NOTE,
    BR.USAGEAMOUNT,
    ovbr.PR_TRANSFER_NO AS PR_TRANSFER_NO,
    ovbo.PO_TRANSFER_NO AS PO_TRANSFER_NO,
    CFPO.PO_CONTRACT_DATE AS CONTRACT_CARRY_FORWARD_PO,
    BR.RESERVEDNO_ADD
FROM OAGWBG_BUDGETRESERVEDITEM BR
LEFT JOIN OAGWBG_BUDGETRESERVEDITEM BR1
	ON BR.PARENTID = BR1.ID
LEFT JOIN OAGWBG_MASTERSTATUS MS
       ON MS."ID" = BR."STATUSID"
LEFT JOIN OAGWBG_BUDGETRESERVED_BANKACCOUNT BB
       ON BR."BUDGETBANKACCOUNTID" = BB."ID"
LEFT JOIN OAGWBG_V_BUDGETRESERVED BS 
        ON BR.BUDGETREVERSEDID = BS.ID
LEFT JOIN (SELECT * FROM OAGWBG_V_EXT_OAGPO_TRANSACTION_STATUS_V a WHERE a.PR_TRANSFER_NO IS NOT NULL) ovbr
		ON ovbr.PR_BUDGET_ACCOUNT = BR.ACCOUNTCODE AND BR.BOOKNUMBER = ovbr.PR_NUMBER 
LEFT JOIN (SELECT * FROM OAGWBG_V_EXT_OAGPO_TRANSACTION_STATUS_V b WHERE b.PO_TRANSFER_NO IS NOT NULL) ovbo
		ON ovbo.PO_BUDGET_ACCOUNT = BR.ACCOUNTCODE AND BR.BOOKNUMBER = ovbo.PO_NUMBER 
LEFT JOIN APPS.OAGPO_TRANSACTION_STATUS_V CFPO
ON (
    CFPO.PR_BUDGET_ACCOUNT = BR.ACCOUNTCODE
    OR (
        CFPO.PO_BUDGET_ACCOUNT = BR.ACCOUNTCODE
        AND NOT EXISTS (
            SELECT 1
            FROM APPS.OAGPO_TRANSACTION_STATUS_V X
            WHERE X.PO_NUMBER = BR.BOOKNUMBER
              AND X.PO_LINE_ID = COALESCE(BR.LINEID, BR1.LINEID)
              AND X.PR_BUDGET_ACCOUNT = BR.ACCOUNTCODE
        )
    )
)
AND CFPO.PO_NUMBER = BR.BOOKNUMBER
AND CFPO.PO_LINE_ID = COALESCE(BR.LINEID, BR1.LINEID)

/
