-- ล้างแถวขยะ: เดือนที่ถูกล้างค่าแล้วเหลือแถว PLANAMOUNT = 0 ค้างอยู่
-- ตาราง: OAGWBG.OAGWBG_BUDGETDISBURSEMENTESTIMATED
-- PREPROD: 172.16.11.19:1541 / SERVICE_NAME=ebs_PRE / User=OAGWBG
--
-- ⚠️ รัน rollback ได้จาก cleanup_rollback.sql (INSERT ครบ 29 คอลัมน์ 41 แถว)
-- ⚠️ ตรวจแล้วว่าไม่มี FK ชี้มาที่ตารางนี้เลย (ALL_CONSTRAINTS CONSTRAINT_TYPE='R' -> 0 rows)

-- ---------- STEP 1: ตรวจก่อน ต้องได้ 41 ----------
SELECT COUNT(*) AS ROWS_TO_DELETE
FROM   OAGWBG.OAGWBG_BUDGETDISBURSEMENTESTIMATED
WHERE  NVL(PLANAMOUNT, 0) = 0
AND    BUDGETGOVERNMENTID IS NOT NULL
AND    BUDGETDISBURSEMENTPLANID IS NULL;
-- => 41  (ปี 2569 = 30 แถว, ปี 2570 = 11 แถว)


-- ---------- STEP 2: ดูรายละเอียดรายการที่กระทบ ----------
SELECT BUDGETGOVERNMENTID,
       BUDGETYEAR,
       COUNT(*)                                               AS TOTAL_MONTHS,
       SUM(CASE WHEN NVL(PLANAMOUNT,0) > 0 THEN 1 ELSE 0 END) AS MONTHS_KEPT,
       SUM(NVL(PLANAMOUNT,0))                                 AS TOTAL_AMT
FROM   OAGWBG.OAGWBG_BUDGETDISBURSEMENTESTIMATED
WHERE  BUDGETGOVERNMENTID IN (
           SELECT BUDGETGOVERNMENTID
           FROM   OAGWBG.OAGWBG_BUDGETDISBURSEMENTESTIMATED
           WHERE  NVL(PLANAMOUNT,0) = 0
           AND    BUDGETGOVERNMENTID IS NOT NULL
           AND    BUDGETDISBURSEMENTPLANID IS NULL
       )
GROUP  BY BUDGETGOVERNMENTID, BUDGETYEAR
ORDER  BY BUDGETYEAR, BUDGETGOVERNMENTID;
-- ผลที่ตรวจไว้เมื่อ 2026-09-09:
--   70117/2569  12 -> 6 เดือน   60,000
--   70155/2569   3 -> 2 เดือน   20,000
--   70759/2569   6 -> 3 เดือน   60,000
--   70775/2569   7 -> 3 เดือน   15,000
--   70815/2569   1 -> 0 เดือน        0   <-- เหลือ 0 แถว (ผู้ใช้ล้างทิ้งไปแล้วจริง)
--   71214/2569  12 -> 3 เดือน   24,000
--   71250/2569   5 -> 3 เดือน   30,000
--   71278/2569   4 -> 3 เดือน   30,000
--   73607/2569   3 -> 2 เดือน   13,600
--   73621/2569   5 -> 3 เดือน    1,500   <-- เคสที่แจ้ง 100-335/2569
--   48436/2570  12 -> 1 เดือน   18,200


-- ---------- STEP 3: ลบจริง ----------
DELETE FROM OAGWBG.OAGWBG_BUDGETDISBURSEMENTESTIMATED
WHERE  NVL(PLANAMOUNT, 0) = 0
AND    BUDGETGOVERNMENTID IS NOT NULL
AND    BUDGETDISBURSEMENTPLANID IS NULL;
-- ต้องได้ 41 rows deleted -- ถ้าไม่ตรง ให้ ROLLBACK;

COMMIT;


-- ---------- STEP 4: ตรวจหลังลบ ----------
SELECT COUNT(*) AS REMAINING_ZERO_ROWS
FROM   OAGWBG.OAGWBG_BUDGETDISBURSEMENTESTIMATED
WHERE  NVL(PLANAMOUNT, 0) = 0
AND    BUDGETGOVERNMENTID IS NOT NULL
AND    BUDGETDISBURSEMENTPLANID IS NULL;
-- => 0

SELECT COUNT(*) AS TOTAL_ROWS FROM OAGWBG.OAGWBG_BUDGETDISBURSEMENTESTIMATED;
-- ก่อนลบ 1553 -> หลังลบต้องได้ 1512

-- เคส 100-335/2569 ต้องเหลือ ม.ค./ก.พ./มี.ค. เดือนละ 500
SELECT MONTH, PLANAMOUNT
FROM   OAGWBG.OAGWBG_BUDGETDISBURSEMENTESTIMATED
WHERE  BUDGETGOVERNMENTID = 73621
ORDER  BY CASE WHEN MONTH >= 10 THEN MONTH - 12 ELSE MONTH END;
