-- ROLLBACK: คืน OAGWBG_R_BUDGETADJUST กลับเป็น v4 (ประเภท 4 เบิกแทนกัน ITEMDETAIL = NULL)
-- ใช้เมื่อ v5 มีปัญหา — ไม่ต้อง rollback โค้ด เพราะ v5 ไม่ได้เพิ่ม/ลบคอลัมน์ แค่เปลี่ยนค่าใน ITEMDETAIL

-- =====================================================================================
-- OAGWBG_R_BUDGETADJUST  (v4)
-- รายงานการเปลี่ยนแปลงงบประมาณประจำปี — เพิ่มคำอธิบายรายการ / ประเภทรายจ่าย / รายการงบประมาณ
-- และเพิ่มฝั่งโอนออก (SENDER) ของประเภท 3 โอนปรับเงินเหลือจ่าย
--
-- ต่อยอดจาก v2 (_brain_OAGBUDGET/20260904_ReportBudgetAdjust_AllTransferTypes)
--
-- สิ่งที่เพิ่มใน v3
--   1) คอลัมน์ ITEMDETAIL       = คำอธิบายรายการ  จาก OAGWBG_BUDGETTRANSFER.ITEMDETAIL
--      คอลัมน์ BUDGETTYPENAME   = ประเภทรายจ่าย   จาก OAGWBG_V_EXT_OAGINV_CATEGORY_CODES_V.BUDGET_TYPE_NAME
--        (ไม่ใช่ EXPENSE_TYPE_NAME — ค่าที่ผู้ใช้ต้องการคือ "ค่าใช้สอย - รายการไม่ผูกพัน" / "เงินรายได้สะสม"
--         ซึ่งอยู่ใน BUDGET_TYPE_NAME ส่วน EXPENSE_TYPE_NAME เป็นชั้นบนกว่า เช่น "ค่าใช้จ่ายดำเนินงาน")
--      คอลัมน์ CATEGORYNAME     = รายการงบประมาณ  จาก OAGWBG_V_EXT_OAGINV_CATEGORY_CODES_V.NAME
--
--   2) branch ใหม่: ประเภท 3 (โอนปรับเงินเหลือจ่าย) ฝั่งโอนออก
--      v2 มีเฉพาะฝั่งรับโอน คอลัมน์ "จำนวนเงินโอนออก" บนรายงานจึงว่างทั้งหมด
--      ฝั่งโอนออกของประเภท 3 ไม่ได้อยู่ใน OAGWBG_BUDGETADJUST (ตรวจ PREPROD 2026-09-07: 0 แถว)
--      แต่อยู่ใน OAGWBG_BUDGETRECEIVEREFUND — 1 แถวต่อ 1 กองเงินที่ถูกตัด
--      (SaveBudgetReservedTransfer ขั้น 3.4) GIVERID ชี้กลับไปแถวต้นทางใน OAGWBG_BUDGETRECEIVE
--      ตรวจ PREPROD 2026-09-07: type 3 มี 28 link, resolve GIVERID เจอครบ 28/28
--
--   3) v4 — เพิ่มฝั่งโอนออกให้ประเภท 2 (โอนเงินกลับ) และ 5 (โอนเงินกลับหลายปี) ด้วย
--      ทั้งคู่ขาดฝั่งโอนออกด้วยเหตุเดียวกับประเภท 3 คือฝั่งโอนออกอยู่ใน BUDGETRECEIVEREFUND
--        ประเภท 2 — 146 link, GIVERID resolve เจอ 145/146 (1 แถวเป็นข้อมูลค้าง ใช้ LEFT JOIN กันหาย)
--        ประเภท 5 — 46 link, GIVERID เป็น NULL ทั้งหมด เพราะ flow ไม่ได้ตัดกองเงินต้นทาง
--                   ต้องประกอบแถวจากฟิลด์ giver บนตัว link แทน (ครบ 46/46)
--
-- หมายเหตุประเภท 4 (เบิกแทนกัน)
--   ไม่มีคำอธิบายรายการ/หมวดรายการจริงให้ดึง — OAGWBG_ACCOUNT_SEGMENT.CATEGORYID เป็นค่าคงที่
--   '0000' ทุกแถว และ DESCRIPTION เก็บแค่คำว่า 'โอนออก' (ตรวจ PREPROD 2026-09-07: 12/12 แถว)
--   จึงปล่อยคอลัมน์ใหม่ทั้ง 3 เป็น NULL แทนที่จะยัดค่าขยะ
--
-- ตรวจสอบบน PREPROD (ebs_PRE) 2026-09-07
-- =====================================================================================

CREATE OR REPLACE FORCE EDITIONABLE VIEW "OAGWBG"."OAGWBG_R_BUDGETADJUST"
( "RECEIVE_ID", "BUDGETYEAR", "DEPARTMENTNAME", "COSTCENTERNAME", "ACTIVITYID", "PRODUCTID",
  "TOTALTRANSFERAMOUNT", "TOTALRECEIVEAMOUNT", "TOTALBALANCEAMOUNT", "ROLETYPE",
  "BUDGETSOURCEID", "TRANSFER_ID", "TRANSFERNO", "TRANSFERTYPE", "TRANSFER_AMOUNT",
  "BUDGETSOURCENAME", "BUDGETPLANNAME", "ACTIVITYNAME", "PRODUCTNAME", "ROUNDNO",
  "ITEMDETAIL", "BUDGETTYPENAME", "CATEGORYNAME" )
AS
-- ============================================================ 1) โอนเปลี่ยนแปลงงบประมาณ — ฝั่งโอนออก
SELECT
    A.ID                                     AS RECEIVE_ID,
    TO_CHAR(NVL(A.BUDGETYEAR, T.BUDGETYEAR)) AS BUDGETYEAR,
    CC.DEPARTMENTNAME                        AS DEPARTMENTNAME,
    CC.NAME                                  AS COSTCENTERNAME,
    A.ACTIVITYID                             AS ACTIVITYID,
    A.PRODUCTID                              AS PRODUCTID,
    A.TOTALTRANSFERAMOUNT                    AS TOTALTRANSFERAMOUNT,
    CAST(NULL AS NUMBER)                     AS TOTALRECEIVEAMOUNT,
    A.REMAININGAMOUNT                        AS TOTALBALANCEAMOUNT,
    'SENDER'                                 AS ROLETYPE,
    A.BUDGETSOURCEID                         AS BUDGETSOURCEID,
    T.ID                                     AS TRANSFER_ID,
    T.TRANSFERNO                             AS TRANSFERNO,
    '1'                                      AS TRANSFERTYPE,
    T.TOTALTRANSFERAMOUNT                    AS TRANSFER_AMOUNT,
    SRCV.NAME                                AS BUDGETSOURCENAME,
    PLANV.NAME                               AS BUDGETPLANNAME,
    ACTV.ACTIVITY_NAME                       AS ACTIVITYNAME,
    PRODV.NAME                               AS PRODUCTNAME,
    TO_CHAR(T.ROUNDNO)                       AS ROUNDNO,
    T.ITEMDETAIL                             AS ITEMDETAIL,
    CAT.BUDGET_TYPE_NAME                    AS BUDGETTYPENAME,
    CAT.NAME                                 AS CATEGORYNAME
FROM OAGWBG_BUDGETTRANSFER T
JOIN OAGWBG_BUDGETADJUST A ON A.BUDGETTRANSFERID = T.ID
LEFT JOIN OAGWBG_V_EXT_OAGGL_COST_CENTER_V     CC    ON CC.ID    = A.COSTCENTERID
LEFT JOIN OAGWBG_V_EXT_BUDGET_SOURCE_V         SRCV  ON SRCV.ID  = A.BUDGETSOURCEID
LEFT JOIN OAGWBG_V_EXT_OAGGL_BUDGET_PLAN_V     PLANV ON PLANV.ID = A.BUDGETPLANID
LEFT JOIN OAGWBG_V_EXT_OAGGL_BUDGET_ACTIVITY_V ACTV
       ON ACTV.ACTIVITY_ID = A.ACTIVITYID AND ACTV.PLAN_ID = A.BUDGETPLANID
LEFT JOIN OAGWBG_V_EXT_OAGGL_BUDGET_PRODUCT_V  PRODV
       ON PRODV.ID = A.PRODUCTID AND PRODV.BUDGETPLANCODE_ID = A.BUDGETPLANID
LEFT JOIN OAGWBG_V_EXT_OAGINV_CATEGORY_CODES_V CAT   ON CAT.ID   = A.CATEGORYID
WHERE T.TRANSFERTYPE = '1'

UNION ALL
-- ============================================================ 1) โอนเปลี่ยนแปลงงบประมาณ — ฝั่งรับโอน
SELECT
    R.ID, TO_CHAR(R.BUDGETYEAR), R.DEPARTMENTNAME, R.COSTCENTERNAME,
    R.ACTIVITYID, R.PRODUCTID,
    CAST(NULL AS NUMBER), R.TOTALRECEIVEAMOUNT, R.TOTALBALANCEAMOUNT,
    'RECEIVER', R.BUDGETSOURCEID,
    T.ID, T.TRANSFERNO, '1', T.TOTALTRANSFERAMOUNT,
    R.BUDGETSOURCEIDNAME, R.PLANNAME, R.ACTIVITYNAME, R.PRODUCTNAME,
    TO_CHAR(T.ROUNDNO),
    T.ITEMDETAIL, CAT.BUDGET_TYPE_NAME, NVL(CAT.NAME, R.CATEGORYNAME)
FROM OAGWBG_BUDGETTRANSFER T
JOIN OAGWBG_BUDGETADJUST    A ON A.BUDGETTRANSFERID = T.ID
JOIN OAGWBG_V_BUDGETRECEIVE R ON R.BUDGETADJUSTID   = A.ID
LEFT JOIN OAGWBG_V_EXT_OAGINV_CATEGORY_CODES_V CAT ON CAT.ID = R.CATEGORYID
WHERE T.TRANSFERTYPE = '1'

UNION ALL
-- ============================================================ 2) โอนเงินกลับ
SELECT
    R.ID, TO_CHAR(R.BUDGETYEAR), R.DEPARTMENTNAME, R.COSTCENTERNAME,
    R.ACTIVITYID, R.PRODUCTID,
    CAST(NULL AS NUMBER), R.TOTALRECEIVEAMOUNT, R.TOTALBALANCEAMOUNT,
    'RECEIVER', R.BUDGETSOURCEID,
    T.ID, T.TRANSFERNO, '2', T.TOTALTRANSFERAMOUNT,
    R.BUDGETSOURCEIDNAME, R.PLANNAME, R.ACTIVITYNAME, R.PRODUCTNAME,
    TO_CHAR(T.ROUNDNO),
    T.ITEMDETAIL, CAT.BUDGET_TYPE_NAME, NVL(CAT.NAME, R.CATEGORYNAME)
FROM OAGWBG_BUDGETTRANSFER T
JOIN OAGWBG_V_BUDGETRECEIVE R
       ON R.BUDGETTRANSFERID = T.ID AND R.BUDGETRECEIVETYPE = 'T'
LEFT JOIN OAGWBG_V_EXT_OAGINV_CATEGORY_CODES_V CAT ON CAT.ID = R.CATEGORYID
WHERE T.TRANSFERTYPE = '2'

UNION ALL
-- ============================================================ 2) โอนเงินกลับ — ฝั่งโอนออก (ใหม่ใน v4)
-- เหมือนประเภท 3 คือฝั่งโอนออกอยู่ใน OAGWBG_BUDGETRECEIVEREFUND
-- GIVERID resolve เจอ 145/146 (ตรวจ PREPROD 2026-09-07) อีก 1 แถวเป็นข้อมูลค้าง
-- จึงใช้ LEFT JOIN แล้ว NVL ไปหาฟิลด์ giver บนตัว link เอง ไม่ให้แถวนั้นหายไปจากรายงาน
SELECT
    RF.ID,
    NVL(TO_CHAR(G.BUDGETYEAR), TO_CHAR(RF.BUDGETYEAR)),
    NVL(G.DEPARTMENTNAME, CCG.DEPARTMENTNAME),
    NVL(G.COSTCENTERNAME, CCG.NAME),
    RF.ACTIVITYID, RF.PRODUCTID,
    RF.TOTALREFUNDAMOUNT, CAST(NULL AS NUMBER), G.TOTALBALANCEAMOUNT,
    'SENDER', RF.BUDGETSOURCEID,
    T.ID, T.TRANSFERNO, '2', T.TOTALTRANSFERAMOUNT,
    NVL(G.BUDGETSOURCEIDNAME, SRCV.NAME),
    NVL(G.PLANNAME, PLANV.NAME),
    NVL(G.ACTIVITYNAME, ACTV.ACTIVITY_NAME),
    NVL(G.PRODUCTNAME, PRODV.NAME),
    TO_CHAR(T.ROUNDNO),
    T.ITEMDETAIL, CAT.BUDGET_TYPE_NAME, NVL(CAT.NAME, G.CATEGORYNAME)
FROM OAGWBG_BUDGETTRANSFER T
JOIN OAGWBG_BUDGETRECEIVEREFUND RF ON RF.TRANSFERID = T.ID
LEFT JOIN OAGWBG_V_BUDGETRECEIVE               G     ON G.ID     = RF.GIVERID
LEFT JOIN OAGWBG_V_EXT_OAGGL_COST_CENTER_V     CCG   ON CCG.ID   = RF.COSTCENTERIDGIVER
LEFT JOIN OAGWBG_V_EXT_BUDGET_SOURCE_V         SRCV  ON SRCV.ID  = RF.BUDGETSOURCEID
LEFT JOIN OAGWBG_V_EXT_OAGGL_BUDGET_PLAN_V     PLANV ON PLANV.ID = RF.BUDGETPLANID
LEFT JOIN OAGWBG_V_EXT_OAGGL_BUDGET_ACTIVITY_V ACTV
       ON ACTV.ACTIVITY_ID = RF.ACTIVITYID AND ACTV.PLAN_ID = RF.BUDGETPLANID
LEFT JOIN OAGWBG_V_EXT_OAGGL_BUDGET_PRODUCT_V  PRODV
       ON PRODV.ID = RF.PRODUCTID AND PRODV.BUDGETPLANCODE_ID = RF.BUDGETPLANID
LEFT JOIN OAGWBG_V_EXT_OAGINV_CATEGORY_CODES_V CAT   ON CAT.ID   = RF.CATEGORYID
WHERE T.TRANSFERTYPE = '2'

UNION ALL
-- ============================================================ 3) โอนปรับเงินเหลือจ่าย — ฝั่งรับโอน
SELECT
    R.ID, TO_CHAR(R.BUDGETYEAR), R.DEPARTMENTNAME, R.COSTCENTERNAME,
    R.ACTIVITYID, R.PRODUCTID,
    CAST(NULL AS NUMBER), R.TOTALRECEIVEAMOUNT, R.TOTALBALANCEAMOUNT,
    'RECEIVER', R.BUDGETSOURCEID,
    T.ID, T.TRANSFERNO, '3', T.TOTALTRANSFERAMOUNT,
    R.BUDGETSOURCEIDNAME, R.PLANNAME, R.ACTIVITYNAME, R.PRODUCTNAME,
    TO_CHAR(T.ROUNDNO),
    T.ITEMDETAIL, CAT.BUDGET_TYPE_NAME, NVL(CAT.NAME, R.CATEGORYNAME)
FROM OAGWBG_BUDGETTRANSFER T
JOIN OAGWBG_V_BUDGETRECEIVE R
       ON R.BUDGETTRANSFERID = T.ID AND R.BUDGETRECEIVETYPE = 'R'
LEFT JOIN OAGWBG_V_EXT_OAGINV_CATEGORY_CODES_V CAT ON CAT.ID = R.CATEGORYID
WHERE T.TRANSFERTYPE = '3'

UNION ALL
-- ============================================================ 3) โอนปรับเงินเหลือจ่าย — ฝั่งโอนออก (ใหม่ใน v3)
-- ฝั่งโอนออกอยู่ใน OAGWBG_BUDGETRECEIVEREFUND: 1 แถว = 1 กองเงินต้นทางที่ถูกตัด
-- TOTALREFUNDAMOUNT คือยอดที่ตัดจากกองนั้นจริง, GIVERID ชี้กลับไปแถวต้นทาง
SELECT
    RF.ID, TO_CHAR(G.BUDGETYEAR), G.DEPARTMENTNAME, G.COSTCENTERNAME,
    G.ACTIVITYID, G.PRODUCTID,
    RF.TOTALREFUNDAMOUNT, CAST(NULL AS NUMBER), G.TOTALBALANCEAMOUNT,
    'SENDER', G.BUDGETSOURCEID,
    T.ID, T.TRANSFERNO, '3', T.TOTALTRANSFERAMOUNT,
    G.BUDGETSOURCEIDNAME, G.PLANNAME, G.ACTIVITYNAME, G.PRODUCTNAME,
    TO_CHAR(T.ROUNDNO),
    T.ITEMDETAIL, CAT.BUDGET_TYPE_NAME, NVL(CAT.NAME, G.CATEGORYNAME)
FROM OAGWBG_BUDGETTRANSFER T
JOIN OAGWBG_BUDGETRECEIVEREFUND RF ON RF.TRANSFERID = T.ID
JOIN OAGWBG_V_BUDGETRECEIVE     G  ON G.ID = RF.GIVERID
LEFT JOIN OAGWBG_V_EXT_OAGINV_CATEGORY_CODES_V CAT ON CAT.ID = G.CATEGORYID
WHERE T.TRANSFERTYPE = '3'

UNION ALL
-- ============================================================ 4) เบิกแทนกัน — ฝั่งโอนออก
SELECT
    OAS.ID, BR.BUDGETYEAR, CC.DEPARTMENTNAME, CC.NAME,
    OAS.ACTIVITYID, OAS.PRODUCTID,
    OAS.TOTALRECEIVEAMOUNT, CAST(NULL AS NUMBER), BR.TOTALREQUESTAMOUNT,
    'SENDER', OAS.BUDGETSOURCEID,
    CAST(NULL AS NUMBER), TO_CHAR(BR.RUNNING), '4', BR.TOTALREQUESTAMOUNT,
    SRCV.NAME, PLANV.NAME, ACTV.ACTIVITY_NAME, PRODV.NAME,
    TO_CHAR(BR.RUNNING),
    CAST(NULL AS VARCHAR2(4000)), CAST(NULL AS VARCHAR2(240)), CAST(NULL AS VARCHAR2(240))
FROM OAGWBG_BUDGETREQUISITION BR
LEFT JOIN OAGWBG_ACCOUNT_SEGMENT OAS
       ON OAS.REFERENCEID = BR.ID AND OAS.REFERENCETABLE = 'BudgetRequisition'
LEFT JOIN OAGWBG_V_EXT_OAGGL_COST_CENTER_V     CC    ON CC.ID    = NVL(OAS.COSTCENTERID, BR.COSTCENTERID)
LEFT JOIN OAGWBG_V_EXT_BUDGET_SOURCE_V         SRCV  ON SRCV.ID  = OAS.BUDGETSOURCEID
LEFT JOIN OAGWBG_V_EXT_OAGGL_BUDGET_PLAN_V     PLANV ON PLANV.ID = OAS.BUDGETPLANID
LEFT JOIN OAGWBG_V_EXT_OAGGL_BUDGET_ACTIVITY_V ACTV
       ON ACTV.ACTIVITY_ID = OAS.ACTIVITYID AND ACTV.PLAN_ID = OAS.BUDGETPLANID
LEFT JOIN OAGWBG_V_EXT_OAGGL_BUDGET_PRODUCT_V  PRODV
       ON PRODV.ID = OAS.PRODUCTID AND PRODV.BUDGETPLANCODE_ID = OAS.BUDGETPLANID
WHERE BR.TRANSFERTYPE = 'O'

UNION ALL
-- ============================================================ 4) เบิกแทนกัน — ฝั่งรับโอน
SELECT
    OAS.ID, BR.BUDGETYEAR, CC.DEPARTMENTNAME, CC.NAME,
    OAS.ACTIVITYID, OAS.PRODUCTID,
    CAST(NULL AS NUMBER), OAS.TOTALRECEIVEAMOUNT, BR.TOTALREQUESTAMOUNT,
    'RECEIVER', OAS.BUDGETSOURCEID,
    CAST(NULL AS NUMBER), TO_CHAR(BR.RUNNING), '4', BR.TOTALREQUESTAMOUNT,
    SRCV.NAME, PLANV.NAME, ACTV.ACTIVITY_NAME, PRODV.NAME,
    TO_CHAR(BR.RUNNING),
    CAST(NULL AS VARCHAR2(4000)), CAST(NULL AS VARCHAR2(240)), CAST(NULL AS VARCHAR2(240))
FROM OAGWBG_BUDGETREQUISITION BR
LEFT JOIN OAGWBG_ACCOUNT_SEGMENT OAS
       ON OAS.REFERENCEID = BR.ID AND OAS.REFERENCETABLE = 'BudgetRequisition'
LEFT JOIN OAGWBG_V_EXT_OAGGL_COST_CENTER_V     CC    ON CC.ID    = NVL(OAS.COSTCENTERID, BR.COSTCENTERID)
LEFT JOIN OAGWBG_V_EXT_BUDGET_SOURCE_V         SRCV  ON SRCV.ID  = OAS.BUDGETSOURCEID
LEFT JOIN OAGWBG_V_EXT_OAGGL_BUDGET_PLAN_V     PLANV ON PLANV.ID = OAS.BUDGETPLANID
LEFT JOIN OAGWBG_V_EXT_OAGGL_BUDGET_ACTIVITY_V ACTV
       ON ACTV.ACTIVITY_ID = OAS.ACTIVITYID AND ACTV.PLAN_ID = OAS.BUDGETPLANID
LEFT JOIN OAGWBG_V_EXT_OAGGL_BUDGET_PRODUCT_V  PRODV
       ON PRODV.ID = OAS.PRODUCTID AND PRODV.BUDGETPLANCODE_ID = OAS.BUDGETPLANID
WHERE BR.TRANSFERTYPE = 'I'

UNION ALL
-- ============================================================ 5) โอนเงินกลับหลายปี
SELECT
    R.ID, TO_CHAR(R.BUDGETYEAR), R.DEPARTMENTNAME, R.COSTCENTERNAME,
    R.ACTIVITYID, R.PRODUCTID,
    CAST(NULL AS NUMBER), R.TOTALRECEIVEAMOUNT, R.TOTALBALANCEAMOUNT,
    'RECEIVER', R.BUDGETSOURCEID,
    T.ID, T.TRANSFERNO, '5', T.TOTALTRANSFERAMOUNT,
    R.BUDGETSOURCEIDNAME, R.PLANNAME, R.ACTIVITYNAME, R.PRODUCTNAME,
    TO_CHAR(T.ROUNDNO),
    T.ITEMDETAIL, CAT.BUDGET_TYPE_NAME, NVL(CAT.NAME, R.CATEGORYNAME)
FROM OAGWBG_BUDGETTRANSFER T
JOIN OAGWBG_V_BUDGETRECEIVE R
       ON R.BUDGETTRANSFERID = T.ID AND R.BUDGETRECEIVETYPE = 'T'
LEFT JOIN OAGWBG_V_EXT_OAGINV_CATEGORY_CODES_V CAT ON CAT.ID = R.CATEGORYID
WHERE T.TRANSFERTYPE = '4'

UNION ALL
-- ============================================================ 5) โอนเงินกลับหลายปี — ฝั่งโอนออก (ใหม่ใน v4)
-- ต่างจากประเภท 2/3 ตรงที่ SaveBudgetTransferReturnMoreYearsDetail ไม่ set GIVERID เลย
-- (NULL ทั้ง 46 แถว ตรวจ PREPROD 2026-09-07) เพราะ flow นี้ไม่ได้ไปตัดกองเงินต้นทาง
-- ผู้ใช้กรอกยอดเอง — ฝั่งโอนออกจึงระบุด้วย DEPARTMENTIDGIVER / COSTCENTERIDGIVER ของ link
-- ส่วนแผนงาน/ผลผลิต/กิจกรรม/หมวด อ่านจากฟิลด์บน link ซึ่งมีครบ 46/46
SELECT
    RF.ID, TO_CHAR(RF.BUDGETYEAR),
    CCG.DEPARTMENTNAME, CCG.NAME,
    RF.ACTIVITYID, RF.PRODUCTID,
    RF.TOTALREFUNDAMOUNT, CAST(NULL AS NUMBER), CAST(NULL AS NUMBER),
    'SENDER', RF.BUDGETSOURCEID,
    T.ID, T.TRANSFERNO, '5', T.TOTALTRANSFERAMOUNT,
    SRCV.NAME, PLANV.NAME, ACTV.ACTIVITY_NAME, PRODV.NAME,
    TO_CHAR(T.ROUNDNO),
    T.ITEMDETAIL, CAT.BUDGET_TYPE_NAME, CAT.NAME
FROM OAGWBG_BUDGETTRANSFER T
JOIN OAGWBG_BUDGETRECEIVEREFUND RF ON RF.TRANSFERID = T.ID
LEFT JOIN OAGWBG_V_EXT_OAGGL_COST_CENTER_V     CCG   ON CCG.ID   = RF.COSTCENTERIDGIVER
LEFT JOIN OAGWBG_V_EXT_BUDGET_SOURCE_V         SRCV  ON SRCV.ID  = RF.BUDGETSOURCEID
LEFT JOIN OAGWBG_V_EXT_OAGGL_BUDGET_PLAN_V     PLANV ON PLANV.ID = RF.BUDGETPLANID
LEFT JOIN OAGWBG_V_EXT_OAGGL_BUDGET_ACTIVITY_V ACTV
       ON ACTV.ACTIVITY_ID = RF.ACTIVITYID AND ACTV.PLAN_ID = RF.BUDGETPLANID
LEFT JOIN OAGWBG_V_EXT_OAGGL_BUDGET_PRODUCT_V  PRODV
       ON PRODV.ID = RF.PRODUCTID AND PRODV.BUDGETPLANCODE_ID = RF.BUDGETPLANID
LEFT JOIN OAGWBG_V_EXT_OAGINV_CATEGORY_CODES_V CAT   ON CAT.ID   = RF.CATEGORYID
WHERE T.TRANSFERTYPE = '4';
