CREATE OR REPLACE VIEW OAGWBG_R_BUDGETOVERLAP_RESERVED AS
WITH TSV_RAW AS (
    SELECT /*+ MATERIALIZE */
           PR_NUMBER, PR_TRANSFER_NO, PR_BUDGET_ACCOUNT,
           PO_NUMBER, PO_TRANSFER_NO, PO_BUDGET_ACCOUNT
    FROM   APPS.OAGPO_TRANSACTION_STATUS_V
),
HEAD AS (
    SELECT BRS.ID, BRS.BUDGETYEAR, BRS.TRANSFERNO, BRS.RESERVATIONNAME, BRS.RESERVATIONTYPE,
           BRS.BUDGETRESERVEDREGION, BRS.DEPARTMENTID, BRS.DEPARTMENTNAME,
           BRS.COSTCENTERID, BRS.COSTCENTERNAME, BRS.TOTALRESERVEDAMOUNT,
           BRS.STATUSID, BRS.STATUSNAME
    FROM   OAGWBG_V_BUDGETRESERVED BRS
    WHERE  BRS.BUDGETRESERVEDREGION = 'C'
),
HEADCAT AS (
    SELECT BUDGETRESERVEDID,
           LISTAGG(CATEGORYNAME, ', ') WITHIN GROUP (ORDER BY CATEGORYNAME) AS CATEGORYNAME
    FROM   (SELECT DISTINCT BUDGETRESERVEDID, CATEGORYNAME
            FROM   OAGWBG_V_BUDGETRESERVED_CATEGORY
            WHERE  CATEGORYNAME IS NOT NULL)
    GROUP BY BUDGETRESERVEDID
),
ALLOC AS (
    SELECT P.TRANSFERNO                AS RESERVED_TRANSFERNO,
           TO_CHAR(RCV.ROUNDNO)        AS ALLOCATE_TRANSFERNO,
           RCV.ROUNDNO                 AS ALLOCATE_SORTNO,
           RCV.COSTCENTERID            AS LINE_COSTCENTERID,
           RCV.COSTCENTERNAME          AS LINE_COSTCENTERNAME,
           RCV.CATEGORYNAME            AS LINE_DESCRIPTION,
           RCV.TOTALRECEIVEAMOUNT      AS ALLOCATEAMOUNT,
           RCV.ID                      AS RECEIVEID
    FROM   OAGWBG_V_BUDGETALLOCATETRANSFER_CATEGORY P
    JOIN   OAGWBG_V_BUDGETALLOCATETRANSFER_CATEGORY C   ON C.REF = P.ID
    JOIN   OAGWBG_V_BUDGETRECEIVE                   RCV ON RCV.BUDGETALLOCATETRANSFERCATEGORYID = C.ID
    WHERE  P.TRANSFERNO IS NOT NULL
),
ITEM AS (
    SELECT BR.ID, BR.BUDGETREVERSEDID, BR.BOOKNUMBER, BR.DESCRIPTION, BR.SUPPLIER,
           BR.ACCOUNTCODE, BR.BUDGETRESERVEDTYPE, BR.OVERLAPYEAR, BR.OVERLAPROUND,
           BR.RESERVEDNO_ADD, BR.USAGEAMOUNT, BR.TOTALBALANCEAMOUNT, BR.NOTE, BR.CREATEON,
           BR.STATUSID,
           CASE WHEN MS.NAME LIKE '%บันทึก%' THEN 'ส่งเรื่องให้พิจารณา' ELSE MS.NAME END AS STATUSNAME,
           COALESCE(ovbo.PO_TRANSFER_NO, ovbr.PR_TRANSFER_NO, BR.TRANSFERNO) AS ALLOCATE_TRANSFERNO
    FROM       OAGWBG_BUDGETRESERVEDITEM BR
    LEFT JOIN  OAGWBG_MASTERSTATUS MS ON MS.ID = BR.STATUSID
    LEFT JOIN  (SELECT * FROM TSV_RAW a WHERE a.PR_TRANSFER_NO IS NOT NULL) ovbr
           ON  ovbr.PR_BUDGET_ACCOUNT = BR.ACCOUNTCODE AND BR.BOOKNUMBER = ovbr.PR_NUMBER
    LEFT JOIN  (SELECT * FROM TSV_RAW b WHERE b.PO_TRANSFER_NO IS NOT NULL) ovbo
           ON  ovbo.PO_BUDGET_ACCOUNT = BR.ACCOUNTCODE AND BR.BOOKNUMBER = ovbo.PO_NUMBER
    WHERE  BR.BUDGETRESERVEDTYPE IN ('EXPAND_PO','EXPAND_PR','CANCEL_PO','CANCEL_PR')
)
SELECT
    'A'                                 AS ROWKIND,
    H.ID                                AS BUDGETRESERVEDID,
    H.BUDGETYEAR                        AS BUDGETYEAR,
    H.TRANSFERNO                        AS TRANSFERNO,
    H.RESERVATIONNAME                   AS RESERVATIONNAME,
    H.RESERVATIONTYPE                   AS RESERVATIONTYPE,
    H.BUDGETRESERVEDREGION              AS BUDGETRESERVEDREGION,
    H.DEPARTMENTID                      AS DEPARTMENTID,
    H.DEPARTMENTNAME                    AS DEPARTMENTNAME,
    H.COSTCENTERID                      AS COSTCENTERID,
    H.COSTCENTERNAME                    AS COSTCENTERNAME,
    H.TOTALRESERVEDAMOUNT               AS TOTALRESERVEDAMOUNT,
    HC.CATEGORYNAME                     AS CATEGORYNAME,
    A.ALLOCATE_TRANSFERNO               AS ALLOCATE_TRANSFERNO,
    A.ALLOCATE_SORTNO                   AS ALLOCATE_SORTNO,
    COSTV.REGIONID                      AS REGIONID,
    COSTV.REGIONNAME                    AS REGIONNAME,
    A.LINE_COSTCENTERID                 AS LINE_COSTCENTERID,
    A.LINE_COSTCENTERNAME               AS LINE_COSTCENTERNAME,
    A.LINE_DESCRIPTION                  AS LINE_DESCRIPTION,
    A.ALLOCATEAMOUNT                    AS ALLOCATEAMOUNT,
    A.RECEIVEID                         AS LINEID,
    CAST(NULL AS NUMBER)                AS ITEMID,
    CAST(NULL AS VARCHAR2(20))          AS BOOKNUMBER,
    CAST(NULL AS VARCHAR2(240))         AS SUPPLIER,
    CAST(NULL AS VARCHAR2(337))         AS ACCOUNTCODE,
    CAST(NULL AS VARCHAR2(50))          AS ITEMRESERVEDTYPE,
    CAST(NULL AS VARCHAR2(20))          AS RESERVEDTYPENAME,
    CAST(NULL AS NUMBER)                AS OVERLAPYEAR,
    CAST(NULL AS NUMBER)                AS OVERLAPROUND,
    CAST(NULL AS VARCHAR2(250))         AS RESERVEDNO_ADD,
    CAST(NULL AS NUMBER)                AS USAGEAMOUNT,
    CAST(NULL AS NUMBER)                AS TOTALBALANCEAMOUNT,
    CAST(NULL AS NVARCHAR2(1000))       AS NOTE,
    H.STATUSID                          AS STATUSID,
    H.STATUSNAME                        AS STATUSNAME,
    CAST(NULL AS TIMESTAMP(6))          AS RESERVEDITEMDATE
FROM       HEAD H
LEFT JOIN  HEADCAT HC ON HC.BUDGETRESERVEDID = H.ID
LEFT JOIN  ALLOC   A  ON A.RESERVED_TRANSFERNO = H.TRANSFERNO
LEFT JOIN  OAGWBG_V_EXT_OAGGL_COST_CENTER_V COSTV ON COSTV.ID = A.LINE_COSTCENTERID

UNION ALL

SELECT
    'I'                                 AS ROWKIND,
    H.ID                                AS BUDGETRESERVEDID,
    H.BUDGETYEAR                        AS BUDGETYEAR,
    H.TRANSFERNO                        AS TRANSFERNO,
    H.RESERVATIONNAME                   AS RESERVATIONNAME,
    H.RESERVATIONTYPE                   AS RESERVATIONTYPE,
    H.BUDGETRESERVEDREGION              AS BUDGETRESERVEDREGION,
    H.DEPARTMENTID                      AS DEPARTMENTID,
    H.DEPARTMENTNAME                    AS DEPARTMENTNAME,
    H.COSTCENTERID                      AS COSTCENTERID,
    H.COSTCENTERNAME                    AS COSTCENTERNAME,
    H.TOTALRESERVEDAMOUNT               AS TOTALRESERVEDAMOUNT,
    HC.CATEGORYNAME                     AS CATEGORYNAME,
    I.ALLOCATE_TRANSFERNO               AS ALLOCATE_TRANSFERNO,
    CAST(NULL AS NUMBER)                AS ALLOCATE_SORTNO,
    CAST(NULL AS VARCHAR2(240))         AS REGIONID,
    CAST(NULL AS VARCHAR2(240))         AS REGIONNAME,
    CAST(NULL AS VARCHAR2(150))         AS LINE_COSTCENTERID,
    CAST(NULL AS VARCHAR2(240))         AS LINE_COSTCENTERNAME,
    I.DESCRIPTION                       AS LINE_DESCRIPTION,
    CAST(NULL AS NUMBER)                AS ALLOCATEAMOUNT,
    CAST(NULL AS NUMBER)                AS LINEID,
    I.ID                                AS ITEMID,
    I.BOOKNUMBER                        AS BOOKNUMBER,
    I.SUPPLIER                          AS SUPPLIER,
    I.ACCOUNTCODE                       AS ACCOUNTCODE,
    I.BUDGETRESERVEDTYPE                AS ITEMRESERVEDTYPE,
    CASE
        WHEN I.BUDGETRESERVEDTYPE IN ('EXPAND_PO','CANCEL_PO') THEN 'มีหนี้'
        WHEN I.BUDGETRESERVEDTYPE IN ('EXPAND_PR','CANCEL_PR') THEN 'ไม่มีหนี้'
        ELSE 'ไม่ระบุ'
    END                                 AS RESERVEDTYPENAME,
    I.OVERLAPYEAR                       AS OVERLAPYEAR,
    I.OVERLAPROUND                      AS OVERLAPROUND,
    I.RESERVEDNO_ADD                    AS RESERVEDNO_ADD,
    I.USAGEAMOUNT                       AS USAGEAMOUNT,
    I.TOTALBALANCEAMOUNT                AS TOTALBALANCEAMOUNT,
    I.NOTE                              AS NOTE,
    I.STATUSID                          AS STATUSID,
    I.STATUSNAME                        AS STATUSNAME,
    I.CREATEON                          AS RESERVEDITEMDATE
FROM       HEAD H
JOIN       ITEM    I  ON I.BUDGETREVERSEDID = H.ID
LEFT JOIN  HEADCAT HC ON HC.BUDGETRESERVEDID = H.ID
