-- OAGWBG.OAGWBG_V_BUDGET_OVERLAPYEAR_CENTRAL_DETAIL_INTERFACE source

CREATE OR REPLACE FORCE EDITIONABLE VIEW "OAGWBG"."OAGWBG_V_BUDGET_OVERLAPYEAR_CENTRAL_DETAIL_INTERFACE" ("WEB_BATCH_NO", "USER_JE_SOURCE_NAME", "REFERENCE4", "REFERENCE5", "LEDGER_ID", "USER_JE_CATEGORY_NAME", "TRANSFER_DATE", "DEFAULT_EFFECTIVE_DATE", "ACTUAL_FLAG", "BUDGET_ENCUMBRANCE_NAME", "CURRENCY_CODE", "ATTRIBUTE3", "ATTRIBUTE4", "LINE_NUMBER", "SEGMENT1", "SEGMENT2", "SEGMENT3", "SEGMENT4", "SEGMENT5", "SEGMENT6", "SEGMENT7", "SEGMENT8", "SEGMENT9", "SEGMENT10", "SEGMENT11", "SEGMENT12", "SEGMENT13", "ENTERED_DR", "ACCOUNTED_DR", "ENTERED_CR", "ACCOUNTED_CR", "REFERENCE1", "CREATED_BY", "LAST_UPDATED_BY", "CREATION_DATE", "LAST_UPDATE_DATE", "REFERENCE10", "ENCUMBRANCE_TYPE", "TRANSFERNO", "RECEIPIENT_ACCOUNT", "SENDER_ACCOUNT", "TYPE", "TRANSFERTYPE") AS 
  WITH BASE AS (
  SELECT 
    BRSC.*,
    BRS.BUDGETYEAR AS BRS_BUDGETYEAR,
    BRS.DEPARTMENTID,
    BRS.COSTCENTERID,
    BRS.BUDGETSOURCEID,
    BRS.TRANSFERNO,
    EAR.BUDGETTYPEID,
    EAR.ACCOUNTNO,
    EAR.SUBACCOUNTNO,
    CC.NAME AS CATEGORY_NAME,
    SC.CONFIG_VALUE AS LEDGER_ID,
    BCC_GIVER.CASH_ACC AS GIVER,
    BCC_RECEIVER.CASH_ACC AS RECEIVER,
    BRS.TRANSFERDATE
  FROM OAGWBG_BUDGETRESERVED_CATEGORY BRSC
  LEFT JOIN OAGWBG_BUDGETRESERVED BRS
    ON BRSC.BUDGETRESERVEDID = BRS.ID
  LEFT JOIN OAGWBG_V_EXT_OAGPO_EXPENSE_ACCOUNT_RULE_V EAR
    ON BRSC.CATEGORYID = EAR.CATEGORYID
  LEFT JOIN OAGWBG_V_EXT_OAGINV_CATEGORY_CODES_V CC
    ON CC.ID = BRSC.CATEGORYID
  LEFT JOIN OAGWBG_BUDGETRESERVED_BANKACCOUNT BRB
  	ON BRB.RESERVEDID = BRS.ID 
  LEFT JOIN OAGWBG_V_EXT_OAGCE_BANK_ACCOUNT_V BCC_GIVER
  	ON BCC_GIVER.BANK_ACCOUNT_ID = BRB.BANKACCOUNTGIVER 
  LEFT JOIN OAGWBG_V_EXT_OAGCE_BANK_ACCOUNT_V BCC_RECEIVER
  	ON BCC_RECEIVER.BANK_ACCOUNT_ID = BRB.BANKACCOUNTRECEIVER  
  LEFT JOIN OAGWBG_SYSTEMCONFIG SC
  	ON SC.CONFIG_KEY = 'Ledger'
  WHERE BRS.ROUNDINTERFACE IS NOT NULL
),
TYPE_MAP AS (
  SELECT 'ENC' AS DOC_TYPE, 'E' AS ACTUAL_FLAG, 'C' AS DRCR_FLAG FROM DUAL
  UNION ALL
  SELECT 'BG', 'B', 'D' FROM DUAL
)

SELECT
  NVL(RBN.BATCHNAME,
  CASE 
    WHEN T.DOC_TYPE = 'ENC' THEN
      'ENC_CARRY_FORWARD_' || B.BUDGETYEAR || '_' ||
      TO_CHAR(NVL(B.TRANSFERDATE, SYSDATE),'YYMMDDHH24MISS')
    ELSE
      'BG_CARRY_FORWARD_' || B.BUDGETYEAR || '_' ||
      TO_CHAR(NVL(B.TRANSFERDATE, SYSDATE),'YYMMDDHH24MISS')
  END ) AS WEB_BATCH_NO,

  'Web Budget' AS USER_JE_SOURCE_NAME,
  'เงินกันเหลื่อมปี ' || B.BUDGETYEAR || '-' || B.DEPARTMENTID || ' เลขที่เงินกัน ' || B.TRANSFERNO AS REFERENCE4,
  'เงินกันเหลื่อมปี ' || B.BUDGETYEAR || '-' || B.DEPARTMENTID || ' เลขที่เงินกัน ' || B.TRANSFERNO AS REFERENCE5,
  B.LEDGER_ID,

  CASE
  	WHEN T.DOC_TYPE = 'ENC' THEN 'Web Encumbrance'
  	ELSE 'Budget - เงินกัน'
  END AS USER_JE_CATEGORY_NAME,
  
  TO_CHAR(B.TRANSFERDATE,'YYYY-MM-DD') AS TRANSFER_DATE,

  CASE 
    WHEN T.DOC_TYPE = 'ENC' THEN (B.BRS_BUDGETYEAR - 543) || '-SEP-30'
    ELSE (B.BRS_BUDGETYEAR - 543) || '-OCT-01'
  END AS DEFAULT_EFFECTIVE_DATE,

  T.ACTUAL_FLAG,

  CASE 
    WHEN T.DOC_TYPE = 'BG' THEN 'OAG_BG_FINAL'
    ELSE ''
  END AS BUDGET_ENCUMBRANCE_NAME,

  'THB' AS CURRENCY_CODE,
  '' AS ATTRIBUTE3,
  B.TRANSFERNO AS ATTRIBUTE4,
  ROW_NUMBER() OVER (
  PARTITION BY B.BUDGETRESERVEDID, T.DOC_TYPE
  ORDER BY 
    B.CATEGORYID,
    B.BUDGETPLANID
  ) AS LINE_NUMBER,

  B.DEPARTMENTID AS SEGMENT1,
  B.COSTCENTERID AS SEGMENT2,
  MOD(B.BUDGETYEAR,100) AS SEGMENT3,

  CASE 
    WHEN T.DOC_TYPE = 'BG' THEN '400'
    ELSE B.BUDGETSOURCEID
  END AS SEGMENT4,

  LPAD(
  NVL(
    TO_CHAR(
      CASE 
        WHEN B.BUDGETPLANID = 90000 THEN 0
        ELSE B.BUDGETPLANID
      END
    ),
    '0')
     ,5,'0') AS SEGMENT5,

  LPAD(NVL(TO_CHAR(B.PRODUCTID),'0'),5,'0') AS SEGMENT6,
  B.ACTIVITYID AS SEGMENT7,
  B.BUDGETTYPEID AS SEGMENT8,
  NVL(B.BUDGETCODEID,'00000000000000000000') AS SEGMENT9,
  B.ACCOUNTNO AS SEGMENT10,
  B.SUBACCOUNTNO AS SEGMENT11,
  '00' AS SEGMENT12,
  '000' AS SEGMENT13,

  B.TOTALRESERVEDAMOUNT AS ENTERED_DR,
  B.TOTALRESERVEDAMOUNT AS ACCOUNTED_DR,
  NULL AS ENTERED_CR,
  NULL AS ACCOUNTED_CR,

  NVL(RBN.BATCHNAME,
  CASE 
    WHEN T.DOC_TYPE = 'ENC' THEN
      'ENC_CARRY_FORWARD_' || B.BUDGETYEAR || '_' ||
      TO_CHAR(NVL(B.TRANSFERDATE, SYSDATE),'YYMMDDHH24MISS')
    ELSE
      'BG_CARRY_FORWARD_' || B.BUDGETYEAR || '_' ||
      TO_CHAR(NVL(B.TRANSFERDATE, SYSDATE),'YYMMDDHH24MISS')
  END ) AS REFERENCE1,

  B.CREATEBY AS CREATED_BY,
  B.UPDATEBY AS LAST_UPDATED_BY,
  B.CREATEON AS CREATION_DATE,
  B.UPDATEON AS LAST_UPDATE_DATE,
  B.CATEGORY_NAME AS REFERENCE10,

  CASE WHEN T.DOC_TYPE = 'ENC' THEN 'Web Encumbrance' ELSE '' END AS ENCUMBRANCE_TYPE,
  B.TRANSFERNO, 
  CASE WHEN T.DOC_TYPE = 'ENC' THEN B.RECEIVER ELSE NULL END AS RECEIPIENT_ACCOUNT,
  CASE WHEN T.DOC_TYPE = 'ENC' THEN NULL ELSE B.GIVER END AS SENDER_ACCOUNT,

  CASE WHEN T.DOC_TYPE = 'ENC' THEN 'O' ELSE 'I' END AS TYPE,
  'CARRYFWD' AS TRANSFERTYPE

FROM BASE B
CROSS JOIN TYPE_MAP T
LEFT JOIN OAGWBG_RECEIVE_BATCH_NO RBN
  ON RBN.ROUNDNO = B.TRANSFERNO
 AND RBN.INTERFACETYPE = 'O'
 AND (
      (T.DOC_TYPE = 'ENC' AND RBN.BATCHNAME LIKE 'ENC%')
   OR (T.DOC_TYPE = 'BG' AND RBN.BATCHNAME LIKE 'BG%')
 )
ORDER BY B.TRANSFERNO, B.ID, T.ACTUAL_FLAG DESC;