-- OAGWBG.OAGWBG_V_BUDGET_OVERLAPYEAR_DETAIL_INTERFACE source

CREATE OR REPLACE FORCE EDITIONABLE VIEW "OAGWBG"."OAGWBG_V_BUDGET_OVERLAPYEAR_DETAIL_INTERFACE" ("WEB_BATCH_NO", "USER_JE_SOURCE_NAME", "REFERENCE4", "REFERENCE5", "LEDGER_ID", "USER_JE_CATEGORY_NAME", "TRANSFER_DATE", "DEFAULT_EFFECTIVE_DATE", "ACTUAL_FLAG", "BUDGET_ENCUMBRANCE_NAME", "CURRENCY_CODE", "ATTRIBUTE3", "ATTRIBUTE4", "LINE_NUMBER", "SEGMENT1", "SEGMENT2", "SEGMENT3", "SEGMENT4", "SEGMENT5", "SEGMENT6", "SEGMENT7", "SEGMENT8", "SEGMENT9", "SEGMENT10", "SEGMENT11", "SEGMENT12", "SEGMENT13", "ENTERED_DR", "ACCOUNTED_DR", "ENTERED_CR", "ACCOUNTED_CR", "REFERENCE1", "CREATED_BY", "LAST_UPDATED_BY", "CREATION_DATE", "LAST_UPDATE_DATE", "REFERENCE10", "TRANSFERNO", "RECEIPIENT_ACCOUNT", "SENDER_ACCOUNT", "TYPE", "TRANSFERTYPE") AS 
  WITH BASE AS (
  SELECT
    I.ID,
    I.CREATEBY,
    I.CREATEON,
    I.UPDATEBY,
    I.UPDATEON,
    I.BUDGETREVERSEDID,
    I.TRANSFERNO AS ITEM_TRANSFERNO,
    I.DESCRIPTION,
    I.ACCOUNTCODE,
    I.TOTALBALANCEAMOUNT,
    BRS.BUDGETYEAR AS BRS_BUDGETYEAR,
    BRS.DEPARTMENTID,
    BRS.COSTCENTERID,
    BRS.BUDGETSOURCEID,
    BRS.TRANSFERNO AS HEADER_TRANSFERNO,
    BRS.TRANSFERDATE,
    SC.CONFIG_VALUE AS LEDGER_ID,
    BCC_GIVER.CASH_ACC AS GIVER,
    BCC_RECEIVER.CASH_ACC AS RECEIVER,
    REGEXP_SUBSTR(I.ACCOUNTCODE, '[^.]+', 1, 1) AS ACC_SEG1,
    REGEXP_SUBSTR(I.ACCOUNTCODE, '[^.]+', 1, 2) AS ACC_SEG2,
    REGEXP_SUBSTR(I.ACCOUNTCODE, '[^.]+', 1, 3) AS ACC_SEG3,
    REGEXP_SUBSTR(I.ACCOUNTCODE, '[^.]+', 1, 4) AS ACC_SEG4,
    REGEXP_SUBSTR(I.ACCOUNTCODE, '[^.]+', 1, 5) AS ACC_SEG5,
    REGEXP_SUBSTR(I.ACCOUNTCODE, '[^.]+', 1, 6) AS ACC_SEG6,
    REGEXP_SUBSTR(I.ACCOUNTCODE, '[^.]+', 1, 7) AS ACC_SEG7,
    REGEXP_SUBSTR(I.ACCOUNTCODE, '[^.]+', 1, 8) AS ACC_SEG8,
    REGEXP_SUBSTR(I.ACCOUNTCODE, '[^.]+', 1, 9) AS ACC_SEG9,
    REGEXP_SUBSTR(I.ACCOUNTCODE, '[^.]+', 1, 10) AS ACC_SEG10,
    REGEXP_SUBSTR(I.ACCOUNTCODE, '[^.]+', 1, 11) AS ACC_SEG11,
    REGEXP_SUBSTR(I.ACCOUNTCODE, '[^.]+', 1, 12) AS ACC_SEG12,
    REGEXP_SUBSTR(I.ACCOUNTCODE, '[^.]+', 1, 13) AS ACC_SEG13,
    NVL(I.TRANSFERNO, BRS.TRANSFERNO) AS TRANSFERNO_KEY
  FROM OAGWBG.OAGWBG_BUDGETRESERVEDITEM I
  LEFT JOIN OAGWBG.OAGWBG_BUDGETRESERVED BRS
    ON I.BUDGETREVERSEDID = BRS.ID
  LEFT JOIN OAGWBG.OAGWBG_BUDGETRESERVED_BANKACCOUNT BRB
    ON I.BUDGETBANKACCOUNTID = BRB.ID
  LEFT JOIN OAGWBG.OAGWBG_V_EXT_OAGCE_BANK_ACCOUNT_V BCC_GIVER
    ON BCC_GIVER.BANK_ACCOUNT_ID = BRB.BANKACCOUNTGIVER
  LEFT JOIN OAGWBG.OAGWBG_V_EXT_OAGCE_BANK_ACCOUNT_V BCC_RECEIVER
    ON BCC_RECEIVER.BANK_ACCOUNT_ID = BRB.BANKACCOUNTRECEIVER
  LEFT JOIN OAGWBG.OAGWBG_SYSTEMCONFIG SC
    ON SC.CONFIG_KEY = 'Ledger'
  WHERE BRS.BUDGETRESERVEDREGION = 'P'
),
TYPE_MAP AS (
  SELECT 'ENC' AS DOC_TYPE, 'E' AS ACTUAL_FLAG FROM DUAL
  UNION ALL
  SELECT 'BG' AS DOC_TYPE, 'B' AS ACTUAL_FLAG FROM DUAL
)
SELECT
  CASE
    WHEN T.DOC_TYPE = 'ENC' THEN 'ENC_CARRY_FORWARD_' || B.BRS_BUDGETYEAR || '_' || B.TRANSFERNO_KEY || '_' || TO_CHAR(NVL(B.TRANSFERDATE, SYSDATE), 'YYMMDDHH24MISS')
    ELSE 'BG_CARRY_FORWARD_' || B.BRS_BUDGETYEAR || '_' || B.TRANSFERNO_KEY || '_' || TO_CHAR(NVL(B.TRANSFERDATE, SYSDATE), 'YYMMDDHH24MISS')
  END AS WEB_BATCH_NO,
  'Web Budget' AS USER_JE_SOURCE_NAME,
  TO_CHAR(UNISTR('\0E40\0E07\0E34\0E19\0E01\0E31\0E19\0E40\0E2B\0E25\0E37\0E48\0E2D\0E21\0E1B\0E35\0020')) || B.BRS_BUDGETYEAR || ' ' || B.TRANSFERNO_KEY AS REFERENCE4,
  TO_CHAR(UNISTR('\0E40\0E07\0E34\0E19\0E01\0E31\0E19\0E40\0E2B\0E25\0E37\0E48\0E2D\0E21\0E1B\0E35\0020')) || B.BRS_BUDGETYEAR || ' ' || B.TRANSFERNO_KEY AS REFERENCE5,
  B.LEDGER_ID,
  CASE
    WHEN T.DOC_TYPE = 'ENC' THEN 'Web Encumbrance'
    ELSE 'Budget - ' || TO_CHAR(UNISTR('\0E40\0E07\0E34\0E19\0E01\0E31\0E19'))
  END AS USER_JE_CATEGORY_NAME,
  TO_CHAR(B.TRANSFERDATE, 'YYYY-MM-DD') AS TRANSFER_DATE,
  (B.BRS_BUDGETYEAR - 543) || '-OCT-01' AS DEFAULT_EFFECTIVE_DATE,
  T.ACTUAL_FLAG,
  CASE
    WHEN T.DOC_TYPE = 'BG' THEN 'OAG_BG_FINAL'
    ELSE ''
  END AS BUDGET_ENCUMBRANCE_NAME,
  'THB' AS CURRENCY_CODE,
  '' AS ATTRIBUTE3,
  B.TRANSFERNO_KEY AS ATTRIBUTE4,
  ROW_NUMBER() OVER (
    PARTITION BY B.BUDGETREVERSEDID, T.DOC_TYPE
    ORDER BY B.ID
  ) AS LINE_NUMBER,
  B.DEPARTMENTID AS SEGMENT1,
  B.COSTCENTERID AS SEGMENT2,
  MOD(B.BRS_BUDGETYEAR, 100) AS SEGMENT3,
  NVL(B.BUDGETSOURCEID, B.ACC_SEG4) AS SEGMENT4,
  NVL(B.ACC_SEG5, '00000') AS SEGMENT5,
  NVL(B.ACC_SEG6, '00000') AS SEGMENT6,
  B.ACC_SEG7 AS SEGMENT7,
  B.ACC_SEG8 AS SEGMENT8,
  NVL(B.ACC_SEG9, '00000000000000000000') AS SEGMENT9,
  B.ACC_SEG10 AS SEGMENT10,
  B.ACC_SEG11 AS SEGMENT11,
  NVL(B.ACC_SEG12, '00') AS SEGMENT12,
  NVL(B.ACC_SEG13, '000') AS SEGMENT13,
  B.TOTALBALANCEAMOUNT AS ENTERED_DR,
  B.TOTALBALANCEAMOUNT AS ACCOUNTED_DR,
  NULL AS ENTERED_CR,
  NULL AS ACCOUNTED_CR,
  CASE
    WHEN T.DOC_TYPE = 'ENC' THEN 'ENC_CARRY_FORWARD_' || B.BRS_BUDGETYEAR || '_' || B.TRANSFERNO_KEY || '_' || TO_CHAR(NVL(B.TRANSFERDATE, SYSDATE), 'YYMMDDHH24MISS')
    ELSE 'BG_CARRY_FORWARD_' || B.BRS_BUDGETYEAR || '_' || B.TRANSFERNO_KEY || '_' || TO_CHAR(NVL(B.TRANSFERDATE, SYSDATE), 'YYMMDDHH24MISS')
  END AS REFERENCE1,
  B.CREATEBY AS CREATED_BY,
  B.UPDATEBY AS LAST_UPDATED_BY,
  B.CREATEON AS CREATION_DATE,
  B.UPDATEON AS LAST_UPDATE_DATE,
  B.DESCRIPTION AS REFERENCE10,
  B.TRANSFERNO_KEY AS TRANSFERNO,
  CASE WHEN T.DOC_TYPE = 'ENC' THEN B.RECEIVER ELSE NULL END AS RECEIPIENT_ACCOUNT,
  CASE WHEN T.DOC_TYPE = 'BG' THEN B.GIVER ELSE NULL END AS SENDER_ACCOUNT,
  'I' AS TYPE,
  'CARRYPRPO' AS TRANSFERTYPE
FROM BASE B
CROSS JOIN TYPE_MAP T
ORDER BY B.TRANSFERNO_KEY, B.ID, T.ACTUAL_FLAG DESC;