-- =====================================================================================
-- ROLLBACK — คืน OAGWBG_R_BUDGETADJUST กลับเป็น v1
-- ดึงจาก PREPROD (ebs_PRE) ด้วย DBMS_METADATA.GET_DDL เมื่อ 2026-09-04 ก่อน deploy v2
--
-- ⚠️ v1 มีข้อจำกัดที่ทราบแล้ว: รายงานออกได้เฉพาะ TRANSFERTYPE '1'
--    (ประเภท 2/3/4 หายทั้งหมด เพราะ join ผ่าน BUDGETRECEIVEIDSOURCE/TARGET ที่เป็น null)
--    และ branch เบิกแทนไม่กรอง ACCOUNT_SEGMENT.REFERENCETABLE
-- =====================================================================================

CREATE OR REPLACE FORCE EDITIONABLE VIEW "OAGWBG"."OAGWBG_R_BUDGETADJUST"
( "RECEIVE_ID", "BUDGETYEAR", "DEPARTMENTNAME", "COSTCENTERNAME", "ACTIVITYID", "PRODUCTID",
  "TOTALTRANSFERAMOUNT", "TOTALRECEIVEAMOUNT", "TOTALBALANCEAMOUNT", "ROLETYPE",
  "BUDGETSOURCEID", "TRANSFER_ID", "TRANSFERNO", "TRANSFERTYPE", "TRANSFER_AMOUNT",
  "BUDGETSOURCENAME", "BUDGETPLANNAME", "ACTIVITYNAME", "PRODUCTNAME" )
AS
  WITH TRANSFER_CTE AS (
    SELECT
        T.ID                  AS TRANSFER_ID,
        T.TRANSFERNO,
        T.TRANSFERTYPE,
        T.TOTALTRANSFERAMOUNT AS TRANSFER_AMOUNT,
        T.BUDGETPLANID,
        T.ACTIVITYID,
        T.PRODUCTID,
        T.BUDGETSOURCEID,
        T.BUDGETRECEIVEIDSOURCE,
        T.BUDGETRECEIVEIDTARGET
    FROM OAGWBG_V_BUDGETTRANSFER T
)

SELECT
    SRC.ID                                 AS RECEIVE_ID,
    TO_CHAR(SRC.BUDGETYEAR)                AS BUDGETYEAR,
    SRC.DEPARTMENTNAME,
    SRC.COSTCENTERNAME,

    TRF.ACTIVITYID,
    TRF.PRODUCTID,

    SRC.TOTALTRANSFERAMOUNT,
    SRC.TOTALRECEIVEAMOUNT,
    SRC.TOTALBALANCEAMOUNT,

    'SENDER'                               AS ROLETYPE,
    TRF.BUDGETSOURCEID,
    TRF.TRANSFER_ID,
    TRF.TRANSFERNO,
    TRF.TRANSFERTYPE,
    TRF.TRANSFER_AMOUNT,
    SRCV.NAME                                AS BUDGETSOURCENAME,
    PLANV.NAME                               AS BUDGETPLANNAME,
    ACTV.ACTIVITY_NAME                       AS ACTIVITYNAME,
    PRODV.NAME                               AS PRODUCTNAME
FROM TRANSFER_CTE TRF
JOIN OAGWBG_V_BUDGETRECEIVE SRC
     ON TRF.BUDGETRECEIVEIDSOURCE = SRC.ID
LEFT JOIN OAGWBG_V_EXT_BUDGET_SOURCE_V SRCV ON TRF.BUDGETSOURCEID = SRCV.ID
LEFT JOIN OAGWBG_V_EXT_OAGGL_BUDGET_PLAN_V PLANV ON TRF.BUDGETPLANID = PLANV.ID
LEFT JOIN OAGWBG_V_EXT_OAGGL_BUDGET_ACTIVITY_V ACTV
       ON TRF.ACTIVITYID   = ACTV.ACTIVITY_ID
      AND TRF.BUDGETPLANID = ACTV.PLAN_ID
LEFT JOIN OAGWBG_V_EXT_OAGGL_BUDGET_PRODUCT_V PRODV
       ON TRF.PRODUCTID    = PRODV.ID
      AND TRF.BUDGETPLANID = PRODV.BUDGETPLANCODE_ID

UNION ALL

SELECT
    RCV.ID                                 AS RECEIVE_ID,
   TO_CHAR( RCV.BUDGETYEAR )               AS BUDGETYEAR,
    RCV.DEPARTMENTNAME,
    RCV.COSTCENTERNAME,

    RCV.ACTIVITYID,
    RCV.PRODUCTID,

    RCV.TOTALTRANSFERAMOUNT,
    RCV.TOTALRECEIVEAMOUNT,
    RCV.TOTALBALANCEAMOUNT,

    'RECEIVER'                            AS ROLETYPE,
    TRF.BUDGETSOURCEID,
    TRF.TRANSFER_ID,
    TRF.TRANSFERNO,
    TRF.TRANSFERTYPE,
    TRF.TRANSFER_AMOUNT,
    SRCV.NAME                                AS BUDGETSOURCENAME,
    PLANV.NAME                               AS BUDGETPLANNAME,
    ACTV.ACTIVITY_NAME                       AS ACTIVITYNAME,
    PRODV.NAME                               AS PRODUCTNAME
FROM TRANSFER_CTE TRF
JOIN OAGWBG_V_BUDGETRECEIVE RCV
     ON TRF.BUDGETRECEIVEIDTARGET = RCV.ID
LEFT JOIN OAGWBG_V_EXT_BUDGET_SOURCE_V SRCV ON TRF.BUDGETSOURCEID = SRCV.ID
LEFT JOIN OAGWBG_V_EXT_OAGGL_BUDGET_PLAN_V PLANV ON TRF.BUDGETPLANID = PLANV.ID
LEFT JOIN OAGWBG_V_EXT_OAGGL_BUDGET_ACTIVITY_V ACTV
       ON TRF.ACTIVITYID   = ACTV.ACTIVITY_ID
      AND TRF.BUDGETPLANID = ACTV.PLAN_ID
LEFT JOIN OAGWBG_V_EXT_OAGGL_BUDGET_PRODUCT_V PRODV
       ON TRF.PRODUCTID    = PRODV.ID
      AND TRF.BUDGETPLANID = PRODV.BUDGETPLANCODE_ID


UNION ALL

SELECT
  OAS.ID                                   AS RECEIVE_ID,
  BR.BUDGETYEAR                            AS BUDGETYEAR,
  BR.DEPARTMENTID                          AS DEPARTMENTNAME,
  EOCCV.NAME                               AS COSTCENTERNAME,

  OAS.ACTIVITYID,
  OAS.PRODUCTID,

  OAS.TOTALRECEIVEAMOUNT                   AS TOTALTRANSFERAMOUNT,
  CAST(NULL AS NUMBER)                     AS TOTALRECEIVEAMOUNT,
  BR.TOTALREQUESTAMOUNT                    AS TOTALBALANCEAMOUNT,

  'SENDER'                                 AS ROLETYPE,
  OAS.BUDGETSOURCEID,
  CAST(NULL AS NUMBER)                     AS TRANSFER_ID,
  CAST(NULL AS VARCHAR2(100))              AS TRANSFERNO,
  '4' AS TRANSFERTYPE,
  BR.TOTALREQUESTAMOUNT                    AS TRANSFER_AMOUNT,
  SRCV.NAME                                 AS BUDGETSOURCENAME,
  PLANV.NAME                                AS BUDGETPLANNAME,
  ACTV.ACTIVITY_NAME                        AS ACTIVITYNAME,
  PRODV.NAME                                AS PRODUCTNAME
FROM OAGWBG_BUDGETREQUISITION BR
LEFT JOIN OAGWBG_ACCOUNT_SEGMENT OAS
  ON OAS.REFERENCEID = BR.ID
LEFT JOIN OAGWBG_V_EXT_BUDGET_SOURCE_V SRCV
  ON OAS.BUDGETSOURCEID = SRCV.ID
LEFT JOIN OAGWBG_V_EXT_OAGGL_BUDGET_PLAN_V PLANV
  ON OAS.BUDGETPLANID   = PLANV.ID
LEFT JOIN OAGWBG_V_EXT_OAGGL_BUDGET_ACTIVITY_V ACTV
  ON OAS.ACTIVITYID     = ACTV.ACTIVITY_ID
 AND OAS.BUDGETPLANID   = ACTV.PLAN_ID
LEFT JOIN OAGWBG_V_EXT_OAGGL_BUDGET_PRODUCT_V PRODV
  ON OAS.PRODUCTID      = PRODV.ID
 AND OAS.BUDGETPLANID   = PRODV.BUDGETPLANCODE_ID
 LEFT JOIN OAGWBG_V_EXT_OAGGL_COST_CENTER_V EOCCV
  ON BR.COSTCENTERID = EOCCV.ID
WHERE BR.TRANSFERTYPE = 'O'

UNION ALL

SELECT
  OAS.ID                                   AS RECEIVE_ID,
  BR.BUDGETYEAR                            AS BUDGETYEAR,
  BR.DEPARTMENTID                          AS DEPARTMENTNAME,
  EOCCV.NAME                               AS COSTCENTERNAME,

  OAS.PRODUCTID,
  OAS.ACTIVITYID,

   CAST(NULL AS NUMBER)                    AS TOTALTRANSFERAMOUNT,
  OAS.TOTALRECEIVEAMOUNT                   AS TOTALRECEIVEAMOUNT,
  BR.TOTALREQUESTAMOUNT                    AS TOTALBALANCEAMOUNT,


  'RECEIVER'                               AS ROLETYPE,
  OAS.BUDGETSOURCEID,
  CAST(NULL AS NUMBER)                     AS TRANSFER_ID,
  CAST(NULL AS VARCHAR2(100))              AS TRANSFERNO,
  '4' AS TRANSFERTYPE,
  BR.TOTALREQUESTAMOUNT                    AS TRANSFER_AMOUNT,
  SRCV.NAME                                 AS BUDGETSOURCENAME,
  PLANV.NAME                                AS BUDGETPLANNAME,
  ACTV.ACTIVITY_NAME                        AS ACTIVITYNAME,
  PRODV.NAME                                AS PRODUCTNAME
FROM OAGWBG_BUDGETREQUISITION BR
LEFT JOIN OAGWBG_ACCOUNT_SEGMENT OAS
  ON OAS.REFERENCEID = BR.ID
LEFT JOIN OAGWBG_V_EXT_BUDGET_SOURCE_V SRCV
  ON OAS.BUDGETSOURCEID = SRCV.ID
LEFT JOIN OAGWBG_V_EXT_OAGGL_BUDGET_PLAN_V PLANV
  ON OAS.BUDGETPLANID   = PLANV.ID
LEFT JOIN OAGWBG_V_EXT_OAGGL_BUDGET_ACTIVITY_V ACTV
  ON OAS.ACTIVITYID     = ACTV.ACTIVITY_ID
 AND OAS.BUDGETPLANID   = ACTV.PLAN_ID
LEFT JOIN OAGWBG_V_EXT_OAGGL_BUDGET_PRODUCT_V PRODV
  ON OAS.PRODUCTID      = PRODV.ID
 AND OAS.BUDGETPLANID   = PRODV.BUDGETPLANCODE_ID
 LEFT JOIN OAGWBG_V_EXT_OAGGL_COST_CENTER_V EOCCV
  ON BR.COSTCENTERID = TO_CHAR(EOCCV.ID)

WHERE BR.TRANSFERTYPE = 'I';
