-- =====================================================================================
-- OAGWBG_R_BUDGETADJUST  (v2)
-- รายงานการเปลี่ยนแปลงงบประมาณประจำปี — ครอบคลุมการโอนครบทั้ง 5 ประเภท
--
-- ปัญหาของ v1:
--   view เดิม join receive ผ่านคอลัมน์บน header (BUDGETRECEIVEIDSOURCE / BUDGETRECEIVEIDTARGET)
--   แต่ข้อมูลจริงมีแต่ TRANSFERTYPE = '1' เท่านั้นที่ set 2 คอลัมน์นี้
--   (ตรวจ PREPROD 2026-09-04: type 2 = 0/308, type 3 = 0/17, type 4 = 0/42)
--   → INNER JOIN ตัดประเภท 2/3/4 ทิ้งหมด รายงาน export ได้เฉพาะประเภท 1
--   และ branch เบิกแทน join OAGWBG_ACCOUNT_SEGMENT โดยไม่กรอง REFERENCETABLE
--   → ลากแถวของ 'BudgetRequestOutside' / 'Project' ติดมาด้วย (184 แถวปลอม จาก 15 แถวจริง)
--
-- v2 เปลี่ยนเป็น join ตามเส้นทางจริงของแต่ละประเภท:
--   1 โอนเปลี่ยนแปลงงบประมาณ  BUDGETTRANSFER('1') -> BUDGETADJUST -> BUDGETRECEIVE(BUDGETADJUSTID)
--   2 โอนเงินกลับ             BUDGETTRANSFER('2') -> BUDGETRECEIVE(BUDGETTRANSFERID) type 'T'
--   3 โอนปรับเงินเหลือจ่าย     BUDGETTRANSFER('3') -> BUDGETRECEIVE(BUDGETTRANSFERID) type 'R'
--   4 เบิกแทนกัน              BUDGETREQUISITION + ACCOUNT_SEGMENT (เอกเทศ, 'O'=โอนออก / 'I'=โอนเข้า)
--   5 โอนเงินกลับหลายปี        BUDGETTRANSFER('4') -> BUDGETRECEIVE(BUDGETTRANSFERID) type 'T'
--
--   *หมายเหตุรหัส: TRANSFERTYPE ในตารางค่า '4' คือ "โอนกลับหลายปี"
--    (SaveBudgetTransferReturnMoreYearsDetail) ไม่ใช่เบิกแทน — view จึง map เป็น '5'
--    และสงวน '4' ไว้ให้เบิกแทน (requisition) ตามความหมายเดิมของ dropdown บนหน้าจอ
--
-- คอลัมน์ใหม่: ROUNDNO = เลขที่ใบโอนที่ใช้จริง
--   BUDGETTRANSFER.ROUNDNO  unique 396/396 (รูปแบบ ปี+orgtype+running เช่น 6912556)
--   BUDGETREQUISITION.RUNNING unique 14/14 (เช่น 6900001)
--   ต่างจาก TRANSFERNO เดิมที่เป็น running เปล่า ๆ ("1" ซ้ำ 153 ใบ ข้ามปีข้ามประเภท)
--   ยังคงคอลัมน์ TRANSFERNO ไว้ครบเพื่อ backward compatibility
--
-- ตรวจสอบบน PREPROD (ebs_PRE) 2026-09-04 — ผลลัพธ์ 297 แถว:
--   type 1 SENDER 31 / RECEIVER 38, type 2 141, type 3 26, type 4 15, type 5 46
-- =====================================================================================

CREATE OR REPLACE FORCE EDITIONABLE VIEW "OAGWBG"."OAGWBG_R_BUDGETADJUST"
( "RECEIVE_ID", "BUDGETYEAR", "DEPARTMENTNAME", "COSTCENTERNAME", "ACTIVITYID", "PRODUCTID",
  "TOTALTRANSFERAMOUNT", "TOTALRECEIVEAMOUNT", "TOTALBALANCEAMOUNT", "ROLETYPE",
  "BUDGETSOURCEID", "TRANSFER_ID", "TRANSFERNO", "TRANSFERTYPE", "TRANSFER_AMOUNT",
  "BUDGETSOURCENAME", "BUDGETPLANNAME", "ACTIVITYNAME", "PRODUCTNAME", "ROUNDNO" )
AS
-- ============================================================ 1) โอนเปลี่ยนแปลงงบประมาณ — ฝั่งโอนออก
SELECT
    A.ID                                     AS RECEIVE_ID,
    TO_CHAR(NVL(A.BUDGETYEAR, T.BUDGETYEAR)) AS BUDGETYEAR,
    CC.DEPARTMENTNAME                        AS DEPARTMENTNAME,
    CC.NAME                                  AS COSTCENTERNAME,
    A.ACTIVITYID                             AS ACTIVITYID,
    A.PRODUCTID                              AS PRODUCTID,
    A.TOTALTRANSFERAMOUNT                    AS TOTALTRANSFERAMOUNT,
    CAST(NULL AS NUMBER)                     AS TOTALRECEIVEAMOUNT,
    A.REMAININGAMOUNT                        AS TOTALBALANCEAMOUNT,
    'SENDER'                                 AS ROLETYPE,
    A.BUDGETSOURCEID                         AS BUDGETSOURCEID,
    T.ID                                     AS TRANSFER_ID,
    T.TRANSFERNO                             AS TRANSFERNO,
    '1'                                      AS TRANSFERTYPE,
    T.TOTALTRANSFERAMOUNT                    AS TRANSFER_AMOUNT,
    SRCV.NAME                                AS BUDGETSOURCENAME,
    PLANV.NAME                               AS BUDGETPLANNAME,
    ACTV.ACTIVITY_NAME                       AS ACTIVITYNAME,
    PRODV.NAME                               AS PRODUCTNAME,
    TO_CHAR(T.ROUNDNO)                       AS ROUNDNO
FROM OAGWBG_BUDGETTRANSFER T
JOIN OAGWBG_BUDGETADJUST A ON A.BUDGETTRANSFERID = T.ID
LEFT JOIN OAGWBG_V_EXT_OAGGL_COST_CENTER_V     CC    ON CC.ID    = A.COSTCENTERID
LEFT JOIN OAGWBG_V_EXT_BUDGET_SOURCE_V         SRCV  ON SRCV.ID  = A.BUDGETSOURCEID
LEFT JOIN OAGWBG_V_EXT_OAGGL_BUDGET_PLAN_V     PLANV ON PLANV.ID = A.BUDGETPLANID
LEFT JOIN OAGWBG_V_EXT_OAGGL_BUDGET_ACTIVITY_V ACTV
       ON ACTV.ACTIVITY_ID = A.ACTIVITYID AND ACTV.PLAN_ID = A.BUDGETPLANID
LEFT JOIN OAGWBG_V_EXT_OAGGL_BUDGET_PRODUCT_V  PRODV
       ON PRODV.ID = A.PRODUCTID AND PRODV.BUDGETPLANCODE_ID = A.BUDGETPLANID
WHERE T.TRANSFERTYPE = '1'

UNION ALL
-- ============================================================ 1) โอนเปลี่ยนแปลงงบประมาณ — ฝั่งรับโอน
SELECT
    R.ID, TO_CHAR(R.BUDGETYEAR), R.DEPARTMENTNAME, R.COSTCENTERNAME,
    R.ACTIVITYID, R.PRODUCTID,
    CAST(NULL AS NUMBER), R.TOTALRECEIVEAMOUNT, R.TOTALBALANCEAMOUNT,
    'RECEIVER', R.BUDGETSOURCEID,
    T.ID, T.TRANSFERNO, '1', T.TOTALTRANSFERAMOUNT,
    R.BUDGETSOURCEIDNAME, R.PLANNAME, R.ACTIVITYNAME, R.PRODUCTNAME,
    TO_CHAR(T.ROUNDNO)
FROM OAGWBG_BUDGETTRANSFER T
JOIN OAGWBG_BUDGETADJUST    A ON A.BUDGETTRANSFERID = T.ID
JOIN OAGWBG_V_BUDGETRECEIVE R ON R.BUDGETADJUSTID   = A.ID
WHERE T.TRANSFERTYPE = '1'

UNION ALL
-- ============================================================ 2) โอนเงินกลับ
SELECT
    R.ID, TO_CHAR(R.BUDGETYEAR), R.DEPARTMENTNAME, R.COSTCENTERNAME,
    R.ACTIVITYID, R.PRODUCTID,
    CAST(NULL AS NUMBER), R.TOTALRECEIVEAMOUNT, R.TOTALBALANCEAMOUNT,
    'RECEIVER', R.BUDGETSOURCEID,
    T.ID, T.TRANSFERNO, '2', T.TOTALTRANSFERAMOUNT,
    R.BUDGETSOURCEIDNAME, R.PLANNAME, R.ACTIVITYNAME, R.PRODUCTNAME,
    TO_CHAR(T.ROUNDNO)
FROM OAGWBG_BUDGETTRANSFER T
JOIN OAGWBG_V_BUDGETRECEIVE R
       ON R.BUDGETTRANSFERID = T.ID AND R.BUDGETRECEIVETYPE = 'T'
WHERE T.TRANSFERTYPE = '2'

UNION ALL
-- ============================================================ 3) โอนปรับเงินเหลือจ่าย
SELECT
    R.ID, TO_CHAR(R.BUDGETYEAR), R.DEPARTMENTNAME, R.COSTCENTERNAME,
    R.ACTIVITYID, R.PRODUCTID,
    CAST(NULL AS NUMBER), R.TOTALRECEIVEAMOUNT, R.TOTALBALANCEAMOUNT,
    'RECEIVER', R.BUDGETSOURCEID,
    T.ID, T.TRANSFERNO, '3', T.TOTALTRANSFERAMOUNT,
    R.BUDGETSOURCEIDNAME, R.PLANNAME, R.ACTIVITYNAME, R.PRODUCTNAME,
    TO_CHAR(T.ROUNDNO)
FROM OAGWBG_BUDGETTRANSFER T
JOIN OAGWBG_V_BUDGETRECEIVE R
       ON R.BUDGETTRANSFERID = T.ID AND R.BUDGETRECEIVETYPE = 'R'
WHERE T.TRANSFERTYPE = '3'

UNION ALL
-- ============================================================ 4) เบิกแทนกัน — ฝั่งโอนออก
SELECT
    OAS.ID, BR.BUDGETYEAR, CC.DEPARTMENTNAME, CC.NAME,
    OAS.ACTIVITYID, OAS.PRODUCTID,
    OAS.TOTALRECEIVEAMOUNT, CAST(NULL AS NUMBER), BR.TOTALREQUESTAMOUNT,
    'SENDER', OAS.BUDGETSOURCEID,
    CAST(NULL AS NUMBER), TO_CHAR(BR.RUNNING), '4', BR.TOTALREQUESTAMOUNT,
    SRCV.NAME, PLANV.NAME, ACTV.ACTIVITY_NAME, PRODV.NAME,
    TO_CHAR(BR.RUNNING)
FROM OAGWBG_BUDGETREQUISITION BR
LEFT JOIN OAGWBG_ACCOUNT_SEGMENT OAS
       ON OAS.REFERENCEID = BR.ID AND OAS.REFERENCETABLE = 'BudgetRequisition'
LEFT JOIN OAGWBG_V_EXT_OAGGL_COST_CENTER_V     CC    ON CC.ID    = NVL(OAS.COSTCENTERID, BR.COSTCENTERID)
LEFT JOIN OAGWBG_V_EXT_BUDGET_SOURCE_V         SRCV  ON SRCV.ID  = OAS.BUDGETSOURCEID
LEFT JOIN OAGWBG_V_EXT_OAGGL_BUDGET_PLAN_V     PLANV ON PLANV.ID = OAS.BUDGETPLANID
LEFT JOIN OAGWBG_V_EXT_OAGGL_BUDGET_ACTIVITY_V ACTV
       ON ACTV.ACTIVITY_ID = OAS.ACTIVITYID AND ACTV.PLAN_ID = OAS.BUDGETPLANID
LEFT JOIN OAGWBG_V_EXT_OAGGL_BUDGET_PRODUCT_V  PRODV
       ON PRODV.ID = OAS.PRODUCTID AND PRODV.BUDGETPLANCODE_ID = OAS.BUDGETPLANID
WHERE BR.TRANSFERTYPE = 'O'

UNION ALL
-- ============================================================ 4) เบิกแทนกัน — ฝั่งรับโอน
SELECT
    OAS.ID, BR.BUDGETYEAR, CC.DEPARTMENTNAME, CC.NAME,
    OAS.ACTIVITYID, OAS.PRODUCTID,
    CAST(NULL AS NUMBER), OAS.TOTALRECEIVEAMOUNT, BR.TOTALREQUESTAMOUNT,
    'RECEIVER', OAS.BUDGETSOURCEID,
    CAST(NULL AS NUMBER), TO_CHAR(BR.RUNNING), '4', BR.TOTALREQUESTAMOUNT,
    SRCV.NAME, PLANV.NAME, ACTV.ACTIVITY_NAME, PRODV.NAME,
    TO_CHAR(BR.RUNNING)
FROM OAGWBG_BUDGETREQUISITION BR
LEFT JOIN OAGWBG_ACCOUNT_SEGMENT OAS
       ON OAS.REFERENCEID = BR.ID AND OAS.REFERENCETABLE = 'BudgetRequisition'
LEFT JOIN OAGWBG_V_EXT_OAGGL_COST_CENTER_V     CC    ON CC.ID    = NVL(OAS.COSTCENTERID, BR.COSTCENTERID)
LEFT JOIN OAGWBG_V_EXT_BUDGET_SOURCE_V         SRCV  ON SRCV.ID  = OAS.BUDGETSOURCEID
LEFT JOIN OAGWBG_V_EXT_OAGGL_BUDGET_PLAN_V     PLANV ON PLANV.ID = OAS.BUDGETPLANID
LEFT JOIN OAGWBG_V_EXT_OAGGL_BUDGET_ACTIVITY_V ACTV
       ON ACTV.ACTIVITY_ID = OAS.ACTIVITYID AND ACTV.PLAN_ID = OAS.BUDGETPLANID
LEFT JOIN OAGWBG_V_EXT_OAGGL_BUDGET_PRODUCT_V  PRODV
       ON PRODV.ID = OAS.PRODUCTID AND PRODV.BUDGETPLANCODE_ID = OAS.BUDGETPLANID
WHERE BR.TRANSFERTYPE = 'I'

UNION ALL
-- ============================================================ 5) โอนเงินกลับหลายปี
SELECT
    R.ID, TO_CHAR(R.BUDGETYEAR), R.DEPARTMENTNAME, R.COSTCENTERNAME,
    R.ACTIVITYID, R.PRODUCTID,
    CAST(NULL AS NUMBER), R.TOTALRECEIVEAMOUNT, R.TOTALBALANCEAMOUNT,
    'RECEIVER', R.BUDGETSOURCEID,
    T.ID, T.TRANSFERNO, '5', T.TOTALTRANSFERAMOUNT,
    R.BUDGETSOURCEIDNAME, R.PLANNAME, R.ACTIVITYNAME, R.PRODUCTNAME,
    TO_CHAR(T.ROUNDNO)
FROM OAGWBG_BUDGETTRANSFER T
JOIN OAGWBG_V_BUDGETRECEIVE R
       ON R.BUDGETTRANSFERID = T.ID AND R.BUDGETRECEIVETYPE = 'T'
WHERE T.TRANSFERTYPE = '4';
