-- =============================================================================
-- CREATE TABLE OAGWBG_USERMANUAL + seed คู่มือเดิม 3 ไฟล์
-- วันที่: 2026-09-15 (อัปเดต: ตัด MANUALNAME, ACTIVE ออก)
-- ใช้กับ: /Document/UserManual (DocumentController)
--
-- ใช้สำหรับติดตั้งใหม่ (environment ที่ยังไม่มีตาราง)
-- ถ้ามีตารางเวอร์ชันแรกอยู่แล้ว → ใช้ alter_usermanual_drop_name_active.sql แทน
--
-- ⚠️ รันก่อน deploy code — ถ้า deploy code ก่อน หน้า UserManual จะ error
-- ⚠️ VARCHAR2 ใช้ CHAR semantics เพื่อให้เก็บภาษาไทยได้ครบความยาว ไม่ว่า NLS_CHARACTERSET จะเป็นอะไร
-- =============================================================================

-- 1. สร้างตาราง
CREATE TABLE OAGWBG_USERMANUAL (
    ID          NUMBER(10) GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    DESCRIPTION VARCHAR2(2000 CHAR),
    FILEPATH    VARCHAR2(1000 CHAR) NOT NULL,
    SEQUENCE    NUMBER(10),
    CREATEBY    NUMBER(10)     DEFAULT -1 NOT NULL,
    CREATEON    TIMESTAMP(6)   DEFAULT SYSTIMESTAMP NOT NULL,
    UPDATEBY    NUMBER(10),
    UPDATEON    TIMESTAMP(6),
    CONSTRAINT PK_OAGWBG_USERMANUAL PRIMARY KEY (ID)
);

COMMENT ON TABLE  OAGWBG_USERMANUAL             IS 'คู่มือการใช้งานระบบ';
COMMENT ON COLUMN OAGWBG_USERMANUAL.ID          IS 'รหัสอ้างอิงที่ใช้ในระบบ';
COMMENT ON COLUMN OAGWBG_USERMANUAL.DESCRIPTION IS 'รายละเอียดเอกสาร';
COMMENT ON COLUMN OAGWBG_USERMANUAL.FILEPATH    IS 'ชื่อไฟล์คู่มือ (relative จาก wwwroot/documents)';
COMMENT ON COLUMN OAGWBG_USERMANUAL.SEQUENCE    IS 'ลำดับการแสดงผล';
COMMENT ON COLUMN OAGWBG_USERMANUAL.CREATEBY    IS 'ผู้สร้าง อ้างอิง OAGWBG_SYSTEMUSER.ID';
COMMENT ON COLUMN OAGWBG_USERMANUAL.CREATEON    IS 'วันที่สร้าง';
COMMENT ON COLUMN OAGWBG_USERMANUAL.UPDATEBY    IS 'ผู้แก้ไข อ้างอิง OAGWBG_SYSTEMUSER.ID';
COMMENT ON COLUMN OAGWBG_USERMANUAL.UPDATEON    IS 'วันที่แก้ไข';

-- 2. Seed ไฟล์เดิม (ชื่อไฟล์ต้องตรงกับไฟล์ใน wwwroot/documents บน server ทุกตัวอักษร)
INSERT INTO OAGWBG_USERMANUAL (FILEPATH, SEQUENCE, CREATEBY)
VALUES ('00.OAG_User_Manual_BGT_[ตัวอย่าง] การจัดการงบประมาณ.pdf', 1, -1);

INSERT INTO OAGWBG_USERMANUAL (FILEPATH, SEQUENCE, CREATEBY)
VALUES ('02.OAG_User_Manual_BGT_[ตัวอย่าง] การจัดการข้อมูลต่างๆ.pdf', 2, -1);

INSERT INTO OAGWBG_USERMANUAL (FILEPATH, SEQUENCE, CREATEBY)
VALUES ('02.OAG_User_Manual_BG_ระบบงบประมาณ_V2.2.pdf', 3, -1);

COMMIT;

-- 3. ยืนยันผล — ต้องได้ 3 แถว และภาษาไทยไม่เพี้ยน
SELECT ID, DESCRIPTION, FILEPATH, SEQUENCE, CREATEBY, CREATEON
FROM   OAGWBG_USERMANUAL
ORDER  BY SEQUENCE;

-- =============================================================================
-- ROLLBACK (ถ้าต้องการยกเลิก)
-- DROP TABLE OAGWBG_USERMANUAL PURGE;
-- หมายเหตุ: ไฟล์ที่อัปโหลดเข้า wwwroot/documents ไม่ถูกลบตาม
-- =============================================================================
