WITH
BR_GRP AS (
  SELECT
    MIN(BR.ID)                          AS ID,
    BR.DEPARTMENTID,
    BR.COSTCENTERID,
    BR.BUDGETYEAR,
    NVL(BR.BUDGETSOURCEID, 100)         AS BUDGETSOURCEID,
    BR.CATEGORYID,
    BR.PRODUCTID,
    BR.ACTIVITYID,
    BR.BUDGETPLANID,
    MAX(BR.NOTE) AS NOTE,
    -- เงินกัน (เฉพาะ BUDGETRECEIVETYPE = 'O' เท่านั้นที่มีค่า) — ใช้แยกยอดคงเหลือรายใบเงินกัน
    BR.BUDGETRESERVEDCATEGORYID,
    MAX(RS.TRANSFERNO)                  AS RESERVEDNO,
    MAX(RS.BUDGETYEAR)                  AS RESERVEDBUDGETYEAR,
    -- BUDGETCODEID จาก JOIN ตาม TYPE
    COALESCE(
      BCC_A.BUDGETCODEID,
      BCC_G.BUDGETCODEID,
      BCY_P1.BUDGETCODEID,
      BCY_P2.BUDGETCODEID
    )                                   AS BUDGETCODEID,
    SUM(NVL(BR.TOTALRECEIVEAMOUNT,  0)) AS TOTALRECEIVEAMOUNT,
    SUM(NVL(BR.TOTALTRANSFERAMOUNT, 0)) AS TOTALTRANSFERAMOUNT,
    SUM(NVL(BR.TOTALBALANCEAMOUNT,  0)) AS TOTALBALANCEAMOUNT,
    SUM(NVL(BR.REFUNDAMOUNT,        0)) AS REFUNDAMOUNT
  FROM OAGWBG_V_BUDGETRECEIVE BR

  -- TYPE = 'A'
  LEFT JOIN OAGWBG_BUDGETALLOCATETRANSFER_CATEGORY BCC_A
    ON  BR.BUDGETRECEIVETYPE     = 'A'
    AND BCC_A.ID                 = BR.BUDGETALLOCATETRANSFERCATEGORYID

  -- TYPE = 'G' + มี BUDGETRECEIVEPERIODID
  LEFT JOIN OAGWBG_BUDGETALLOCATETRANSFER_CATEGORY BCC_G
    ON  BR.BUDGETRECEIVETYPE     = 'G'
    AND BR.BUDGETRECEIVEPERIODID IS NULL
    AND BCC_G.ID                 = BR.BUDGETALLOCATETRANSFERCATEGORYID

  -- ELSE  ดึง BRP ก่อน
  LEFT JOIN OAGWBG_BUDGETRECEIVEPERIOD BRP
    ON  BR.BUDGETRECEIVETYPE     NOT IN ('A')
    AND BRP.ID                   = BR.BUDGETRECEIVEPERIODID

  -- ELSE + PERIOD_TYPE = 1
  LEFT JOIN OAGWBG_BUDGETCODE_YEAR BCY_P1
    ON  BR.BUDGETRECEIVETYPE     NOT IN ('A')
    AND BRP.PERIOD_TYPE          = 1
    AND BCY_P1.BUDGETYEAR        = BR.BUDGETYEAR
    AND BCY_P1.CATEGORYID        = BR.CATEGORYID
    AND BCY_P1.PRODUCTID         = BR.PRODUCTID
    AND BCY_P1.ACTIVITYCODEID        = BR.ACTIVITYID

  -- ELSE + PERIOD_TYPE != 1
  LEFT JOIN OAGWBG_BUDGETCODEMORE_YEAR BCY_P2
    ON  BR.BUDGETRECEIVETYPE     NOT IN ('A')
    AND NVL(BRP.PERIOD_TYPE, 0)  != 1
    AND BCY_P2.BUDGETYEAR        = BR.BUDGETYEAR
    AND BCY_P2.CATEGORYID        = BR.CATEGORYID
    AND BCY_P2.PRODUCTID         = BR.PRODUCTID
    AND BCY_P2.ACTIVITYCODEID        = BR.ACTIVITYID
    AND BCY_P2.BUDGETGOVERNMENTID = BRP.BUDGETGOVERNMENTID
    AND BCY_P2.BUDGETSOURCEID    = BRP.BUDGETSOURCEID

  -- เงินกัน: BUDGETRECEIVE.BUDGETRESERVEDCATEGORYID -> ใบเงินกัน (ทั้งคู่เป็น PK จึงเป็น many-to-one ไม่เกิด fan-out)
  LEFT JOIN OAGWBG_BUDGETRESERVED_CATEGORY RSC
    ON  RSC.ID = BR.BUDGETRESERVEDCATEGORYID
  LEFT JOIN OAGWBG_BUDGETRESERVED RS
    ON  RS.ID  = RSC.BUDGETRESERVEDID

  WHERE BR.BUDGETRECEIVETYPE NOT IN ('T', 'R')

  GROUP BY
    BR.DEPARTMENTID,
    BR.COSTCENTERID,
    BR.BUDGETYEAR,
    NVL(BR.BUDGETSOURCEID, 100),
    BR.CATEGORYID,
    BR.PRODUCTID,
    BR.ACTIVITYID,
    BR.BUDGETPLANID,
    BR.BUDGETRESERVEDCATEGORYID,
    COALESCE(                        -- << ต้องใส่ใน GROUP BY ด้วย
      BCC_A.BUDGETCODEID,
      BCC_G.BUDGETCODEID,
      BCY_P1.BUDGETCODEID,
      BCY_P2.BUDGETCODEID
    )
),

CC_DIM AS ( 
  SELECT
    ID,
    MAX(DEPARTMENTNAME) AS DEPARTMENTNAME,
    MAX(NAME)           AS NAME
  FROM OAGWBG_V_EXT_OAGGL_COST_CENTER_V
  GROUP BY ID
),

EXTCC_DIM AS (  
  SELECT
    ID,
    MAX(NAME)             AS NAME,
    MAX(BUDGET_TYPE_ID)   AS BUDGET_TYPE_ID,
    MAX(BUDGET_TYPE_NAME) AS BUDGET_TYPE_NAME
  FROM OAGWBG_V_EXT_OAGINV_CATEGORY_CODES_V
  GROUP BY ID
),

BP_DIM AS (   
  SELECT ID, MAX(NAME) AS DESCRIPTION
  FROM OAGWBG_V_EXT_OAGGL_BUDGET_PRODUCT_V
  GROUP BY ID
),

BA_DIM AS (     
  SELECT ACTIVITY_ID, MAX(ACTIVITY_NAME) AS DESCRIPTION
  FROM OAGWBG_V_EXT_OAGGL_BUDGET_ACTIVITY_V
  GROUP BY ACTIVITY_ID
),

P_DIM AS (     
  SELECT ID, NAME AS PLANNAME
  FROM OAGWBG_V_EXT_OAGGL_BUDGET_PLAN_V
  GROUP BY ID, NAME
)

SELECT
  A.ID,
  A.DEPARTMENTID,
  CC.DEPARTMENTNAME,
  A.COSTCENTERID,
  CC.NAME                 AS COSTCENTERNAME,
  A.BUDGETYEAR,
  A.BUDGETSOURCEID,
  A.BUDGETCODEID,
  A.CATEGORYID,
  EXTCC.BUDGET_TYPE_ID    AS BUDGETTYPEID,
  EXTCC.BUDGET_TYPE_NAME  AS BUDGETTYPENAME,
  EXTCC.NAME              AS CATEGORYNAME,
  A.PRODUCTID,
  BP.DESCRIPTION          AS PRODUCTNAME,
  A.ACTIVITYID,
  BA.DESCRIPTION          AS ACTIVITYNAME,
  A.BUDGETPLANID,
  PD.PLANNAME             AS PLANNAME,
  0                       AS TOTALREQUESTAMOUNT,
  0                       AS TOTALALLOCATEAMOUNT,
  A.TOTALRECEIVEAMOUNT,
  A.TOTALTRANSFERAMOUNT,
  A.TOTALBALANCEAMOUNT,
  A.REFUNDAMOUNT,
  A.NOTE,
  A.BUDGETRESERVEDCATEGORYID,
  A.RESERVEDNO,
  A.RESERVEDBUDGETYEAR
  
FROM BR_GRP A
LEFT JOIN CC_DIM    CC    ON CC.ID          = A.COSTCENTERID
LEFT JOIN EXTCC_DIM EXTCC ON EXTCC.ID       = A.CATEGORYID
LEFT JOIN BP_DIM    BP    ON BP.ID          = A.PRODUCTID
LEFT JOIN BA_DIM    BA    ON BA.ACTIVITY_ID = A.ACTIVITYID
LEFT JOIN P_DIM     PD    ON PD.ID          = A.BUDGETPLANID
ORDER BY
  A.BUDGETYEAR,
  A.DEPARTMENTID,
  A.COSTCENTERID,
  A.BUDGETSOURCEID,
  A.CATEGORYID,
  A.PRODUCTID,
  A.ACTIVITYID,
  A.BUDGETPLANID
